project:
  type: website
  output-dir: _site

metadata:
  author: "Byungkook Oh"

execute:
  freeze: auto

format:
  # https://quarto.org/docs/reference/formats/html.html
  # https://quarto.org/docs/output-formats/html-themes.html
  html:
    fontsize: 16.5px
    toc: true
    toc-title: "On this page"
    toc-location: right
    # number-sections: true
    # code-overflow: wrap
    date-modified: last-modified
    date-format: "YYYY.MM.DD"
    theme:
      light: [flatly, style.scss]  # flatly, cosmo, litera
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

website:
  title: "Machine Learning"
  # Quarto 빌드 시 canonical URL, sitemap 등의 base URL을 gli.konkuk.ac.kr 기준으로 생성하도록 설정
  site-url: https://gli.konkuk.ac.kr/board/lectures/machine-learning
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/index.qmd
        text: Exercises 
      - href: assignments/index.qmd
        text: Assignments
      - icon: link-45deg
        href: http://gli.konkuk.ac.kr
        text: GLI Lab
    tools:
      - icon: github
        href: https://github.com/GLI-Lab/machine-learning-course
        text: Machine Learning Course GitHub

  sidebar:
    - id: exercises
      title: "Exercises"
      style: "floating"
      collapse-level: 2
      contents:
        - section: "Exercises"
          href: exercises/index.qmd
          contents:
            - exercises/environment-setup.qmd
            - section: "Lab1. Introduction to ML"
              contents:
                - text: "Python Basics (⭐)"
                  href: exercises/lab01/python-basics.qmd
                - text: "Numpy Basics (⭐⭐)"
                  href: exercises/lab01/numpy-basics.qmd
                - text: "Matplotlib Basics"
                  href: exercises/lab01/matplotlib-basics.qmd
                - text: "Pandas Basics"
                  href: exercises/lab01/pandas-basics.qmd
            - section: "Lab2. Linear Models"
              contents:
                - text: "Linear Regression"
                  href: exercises/lab02/linear-regression.qmd
                - text: "Logistic Regression"
                  href: exercises/lab02/logistic-regression.qmd
                - text: "Classification Metrics"
                  href: exercises/lab02/classification-metrics.qmd
                - text: "Softmax Regression"
                  href: exercises/lab02/softmax-regression.qmd
            - section: "Lab3. Multi-Layer Perceptron"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab4. Model Validation"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab5. Model Generalization"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab6. Convolutional NNs"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab7. Recurrent NNs"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab9. Attention Mechanisms"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab10. Generative Models"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab11. Representations"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmdd
            - section: "Lab12. SVM and Kernels"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab13. Decision Trees"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab14. Ensemble Methods"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
            - section: "Lab15. Bayesian Learning"
              contents:
                - text: "TBA1"
                  # href: exercises/lab14-naive-bayes.qmd
                - text: "TBA2"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
                - text: "TBA3"
                  # href: exercises/lab02/lab02-01-perceptron-limits.qmd
    - id: assignments
      title: "Assignments"
      collapse-level: 1
      align: left
      contents:
        - section: "Assignments"
          href: assignments/index.qmd
          contents:
            - text: "HW1 (~26.03.29)"
              href: assignments/hw01/hw01.qmd
            - text: "HW2 (~26.04.05)"
              href: assignments/hw02/hw02.qmd
            - text: "HW3 (~TBA)"
              href: assignments/hw03/hw03.qmd
            - text: "HW4 (~TBA)"
              href: assignments/hw04/hw04.qmd
            - text: "HW5 (~TBA)"
              href: assignments/hw05/hw05.qmd
            - text: "HW6 (~TBA)"
              href: assignments/hw06/hw06.qmd
            - text: "HW7 (~TBA)"
              href: assignments/hw07/hw07.qmd
            - text: "HW8 (~TBA)"
              href: assignments/hw08/hw08.qmd
