{
  "hash": "c7474d883eaeb86d1e20d106ede5e963",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Lab9-1. CNN Architecture Design & Parameter Counting\"\njupyter: python3\n---\n\n\n[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/GLI-Lab/machine-learning-course/blob/students/exercises/lab09/cnn-parameters.ipynb)\n\n## Objectives\n\n- Understand the **parameter count formula** for convolutional layers and apply it manually.\n- Track how **spatial dimensions** (height, width) propagate through a CNN given kernel size, stride, and padding.\n- Design a complete **CNN architecture** for a small image classification task and predict its total parameter count before running any code.\n- Verify your hand-computed counts against PyTorch's `model.parameters()`.\n- Analyze how **filter size, channel width, and stride** affect parameter count, and observe where parameters tend to concentrate in a typical CNN.\n\n## Background\n\n### Why Count Parameters?\n\nThe number of trainable parameters in a model determines three practical things at once: how much GPU memory the model occupies, how many FLOPs each forward pass requires, and how much data you need to train it without overfitting. Modern image models range from a few hundred thousand parameters (MobileNet variants) to billions (ViT-22B). Knowing how to estimate this number for any architecture is one of the first instincts a deep learning practitioner develops, because it tells you immediately whether a design is feasible on your hardware budget.\n\n### Convolutional Layer Parameter Count\n\nA 2D convolutional layer is defined by four hyperparameters: the input channel count $C_{in}$, the output channel count $C_{out}$, the kernel height $K_h$, and the kernel width $K_w$. Each output channel is produced by a separate filter that spans **all** input channels, so a single filter has $C_{in} \\times K_h \\times K_w$ weights. With $C_{out}$ filters and one bias per filter, the total parameter count is:\n\n$$P_{\\text{conv}} = (C_{in} \\times K_h \\times K_w + 1) \\times C_{out}$$\n\nThe \"$+1$\" is the bias term per output channel. Note that this count is **independent of the spatial size** of the input. The same conv layer applied to a 32×32 image and to a 224×224 image has exactly the same parameter count, because the same filter is reused at every spatial position. This weight sharing is what makes CNNs so parameter-efficient compared to fully connected networks.\n\n### Output Spatial Dimensions\n\nAfter convolution with stride $S$ and zero-padding $P$ on each side, the output spatial size is:\n\n$$H_{out} = \\left\\lfloor \\frac{H_{in} + 2P - K_h}{S} \\right\\rfloor + 1$$\n\nThe same formula applies to the width. Pooling layers follow the same rule but typically use $K = S = 2$, which halves the spatial size at each pooling stage.\n\n### Other Layer Types\n\nPooling layers (max pool, average pool) have **zero** parameters. They reduce spatial size but do not introduce weights. Batch normalization layers add $2C$ parameters per channel (a scale and a shift), plus running statistics that are not trainable. A fully connected layer with $M$ inputs and $N$ outputs has $(M + 1) \\times N$ parameters. The location where features are flattened (the transition from the last conv block to the first FC layer) is usually where parameters accumulate, because the input to the FC layer is the entire flattened feature map.\n\n## 0. Setup\n\n::: {#b368cab4 .cell execution_count=1}\n``` {.python .cell-code}\nimport torch\nimport torch.nn as nn\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nsns.set_theme(style='whitegrid', font_scale=1.15)\ntorch.manual_seed(42)\nnp.random.seed(42)\n```\n:::\n\n\n## 1. Parameters of a Single Conv Layer\n\nLet us start small: one convolutional layer, computed by hand, then verified.\n\n### 1.1 The Formula in Action\n\nConsider a `Conv2d` layer that takes 3-channel RGB images and outputs 16 feature maps using 3×3 filters:\n\n::: {#166a0c32 .cell execution_count=2}\n``` {.python .cell-code}\nconv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)\nprint(conv1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n```\n:::\n:::\n\n\nPlugging into the formula with $C_{in}=3$, $C_{out}=16$, $K_h = K_w = 3$:\n\n$$P = (3 \\times 3 \\times 3 + 1) \\times 16 = (27 + 1) \\times 16 = 28 \\times 16 = 448$$\n\nLet's verify:\n\n::: {#8aa563bd .cell execution_count=3}\n``` {.python .cell-code}\ndef count_params(module):\n    return sum(p.numel() for p in module.parameters() if p.requires_grad)\n\nprint(f\"Hand-computed: 448\")\nprint(f\"PyTorch count: {count_params(conv1)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHand-computed: 448\nPyTorch count: 448\n```\n:::\n:::\n\n\nWe can also inspect the shapes of the weight tensor and bias tensor directly:\n\n::: {#92b5959e .cell execution_count=4}\n``` {.python .cell-code}\nprint(f\"Weight shape: {conv1.weight.shape}\")  # (out_channels, in_channels, K_h, K_w)\nprint(f\"Bias shape  : {conv1.bias.shape}\")    # (out_channels,)\nprint(f\"Weight count: {conv1.weight.numel()}\")\nprint(f\"Bias count  : {conv1.bias.numel()}\")\nprint(f\"Total       : {conv1.weight.numel() + conv1.bias.numel()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWeight shape: torch.Size([16, 3, 3, 3])\nBias shape  : torch.Size([16])\nWeight count: 432\nBias count  : 16\nTotal       : 448\n```\n:::\n:::\n\n\nThe weight tensor has shape `(C_out, C_in, K_h, K_w)`. This is the canonical layout for 2D convolution weights in PyTorch and makes the multiplication structure explicit: 16 output filters, each 3×3 in size, applied to 3 input channels.\n\n::: {.callout-tip}\n## Spotting the Bias Quickly\n\nWhen verifying parameter counts, a useful sanity check is `params_total - params_weights == out_channels`. If the difference equals the number of output channels, you know the layer has bias enabled. PyTorch's `Conv2d` enables bias by default, but architectures using BatchNorm typically set `bias=False` because the BatchNorm shift parameter makes the conv bias redundant.\n:::\n\n### 1.2 Tracking Output Spatial Size\n\nLet's pass a dummy 32×32 RGB image through `conv1` and confirm the output size matches the formula. With $H_{in}=32$, $K=3$, $P=1$, $S=1$:\n\n$$H_{out} = \\left\\lfloor \\frac{32 + 2 \\cdot 1 - 3}{1} \\right\\rfloor + 1 = 31 + 1 = 32$$\n\nPadding of 1 with kernel size 3 and stride 1 preserves the spatial dimension. This is the most common configuration in modern CNNs.\n\n::: {#ce0f5d58 .cell execution_count=5}\n``` {.python .cell-code}\nx = torch.randn(1, 3, 32, 32)  # (batch, channels, H, W)\nout = conv1(x)\nprint(f\"Input  shape: {tuple(x.shape)}\")\nprint(f\"Output shape: {tuple(out.shape)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput  shape: (1, 3, 32, 32)\nOutput shape: (1, 16, 32, 32)\n```\n:::\n:::\n\n\n## 2. Tracking Spatial Dimensions Through a Network\n\nIn a CNN the spatial size and channel count change at every layer. The pattern in most practical architectures is the same: spatial size shrinks (via pooling or strided conv) while channel count grows. This trades resolution for richer feature representations.\n\n::: {#eae0f515 .cell execution_count=6}\n``` {.python .cell-code}\ndef trace_shapes(layers, input_shape):\n    \"\"\"Pass a dummy tensor through each layer and print the shape after each.\"\"\"\n    x = torch.randn(*input_shape)\n    print(f\"{'Layer':<25}{'Output Shape':<25}{'Params':>10}\")\n    print(f\"{'Input':<25}{str(tuple(x.shape)):<25}{'':>10}\")\n    for name, layer in layers:\n        x = layer(x)\n        n_params = sum(p.numel() for p in layer.parameters())\n        print(f\"{name:<25}{str(tuple(x.shape)):<25}{n_params:>10,}\")\n    return x\n```\n:::\n\n\nLet's trace a small block: conv, pool, conv, pool.\n\n::: {#b044cb3c .cell execution_count=7}\n``` {.python .cell-code}\nlayers = [\n    (\"Conv 3->16, 3x3, p=1\",  nn.Conv2d(3, 16, 3, padding=1)),\n    (\"MaxPool 2x2\",           nn.MaxPool2d(2)),\n    (\"Conv 16->32, 3x3, p=1\", nn.Conv2d(16, 32, 3, padding=1)),\n    (\"MaxPool 2x2\",           nn.MaxPool2d(2)),\n]\n_ = trace_shapes(layers, input_shape=(1, 3, 32, 32))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLayer                    Output Shape                 Params\nInput                    (1, 3, 32, 32)                     \nConv 3->16, 3x3, p=1     (1, 16, 32, 32)                 448\nMaxPool 2x2              (1, 16, 16, 16)                   0\nConv 16->32, 3x3, p=1    (1, 32, 16, 16)               4,640\nMaxPool 2x2              (1, 32, 8, 8)                     0\n```\n:::\n:::\n\n\nThree patterns emerge from the trace. First, each `MaxPool2d(2)` halves both height and width but adds **zero** parameters. Second, each conv layer with `padding=1, kernel=3` preserves spatial size while changing only the channel dimension. Third, the parameter count of conv layers grows quadratically with the channel count, since the formula contains $C_{in} \\times C_{out}$ as the dominant term.\n\n## 3. Designing a Full CNN for CIFAR-10\n\nOur task: build a CNN classifier for CIFAR-10. Input images are 32×32 RGB, and there are 10 output classes. We will use a standard \"VGG-style\" pattern of repeated `[Conv -> ReLU -> Conv -> ReLU -> MaxPool]` blocks followed by a small FC head.\n\n### 3.1 Architecture Specification\n\nThe architecture we target proceeds in three convolutional blocks followed by a fully connected head. Block 1 applies `Conv 3 -> 32` and `Conv 32 -> 32`, then `MaxPool` to reduce the spatial size from 32×32 to 16×16. Block 2 applies `Conv 32 -> 64` and `Conv 64 -> 64`, followed by `MaxPool` to reach 8×8. Block 3 applies `Conv 64 -> 128` and `Conv 128 -> 128`, then `MaxPool` to arrive at 4×4 with 128 channels. We then flatten the output to a vector of length $128 \\times 4 \\times 4 = 2048$, pass it through `Linear 2048 -> 256` with ReLU, and finally through `Linear 256 -> 10` to produce class logits.\n\nAll conv layers use 3×3 kernels with padding 1, and all pooling is 2×2 with stride 2.\n\n### 3.2 Hand-Computing the Parameter Counts\n\nBefore writing any PyTorch code, let's compute every layer's parameter count by hand using the formulas from the Background section. This is a skill worth practicing: experienced practitioners do this on a whiteboard before committing to an architecture.\n\nFor Block 1, `Conv 3 -> 32, 3x3` gives $(3 \\cdot 3 \\cdot 3 + 1) \\cdot 32 = 28 \\cdot 32 = 896$, and `Conv 32 -> 32, 3x3` gives $(32 \\cdot 9 + 1) \\cdot 32 = 289 \\cdot 32 = 9{,}248$.\n\nFor Block 2, `Conv 32 -> 64, 3x3` gives $(32 \\cdot 9 + 1) \\cdot 64 = 289 \\cdot 64 = 18{,}496$, and `Conv 64 -> 64, 3x3` gives $(64 \\cdot 9 + 1) \\cdot 64 = 577 \\cdot 64 = 36{,}928$.\n\nFor Block 3, `Conv 64 -> 128, 3x3` gives $(64 \\cdot 9 + 1) \\cdot 128 = 577 \\cdot 128 = 73{,}856$, and `Conv 128 -> 128, 3x3` gives $(128 \\cdot 9 + 1) \\cdot 128 = 1{,}153 \\cdot 128 = 147{,}584$.\n\nFor the FC head, `Linear 2048 -> 256` gives $(2048 + 1) \\cdot 256 = 524{,}544$, and `Linear 256 -> 10` gives $(256 + 1) \\cdot 10 = 2{,}570$.\n\nAdding all of these together:\n\n$$P_{\\text{total}} = 896 + 9248 + 18496 + 36928 + 73856 + 147584 + 524544 + 2570 = 814{,}122$$\n\nNow let's verify against PyTorch.\n\n### 3.3 Building the Network in PyTorch\n\n::: {#5e0b3f11 .cell execution_count=8}\n``` {.python .cell-code}\nclass SmallVGG(nn.Module):\n    def __init__(self, num_classes=10):\n        super().__init__()\n        self.features = nn.Sequential(\n            # Block 1\n            nn.Conv2d(3, 32, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.Conv2d(32, 32, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.MaxPool2d(2),                              # 32x32 -> 16x16\n            # Block 2\n            nn.Conv2d(32, 64, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.Conv2d(64, 64, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.MaxPool2d(2),                              # 16x16 -> 8x8\n            # Block 3\n            nn.Conv2d(64, 128, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.Conv2d(128, 128, kernel_size=3, padding=1),\n            nn.ReLU(inplace=True),\n            nn.MaxPool2d(2),                              # 8x8 -> 4x4\n        )\n        self.classifier = nn.Sequential(\n            nn.Flatten(),\n            nn.Linear(128 * 4 * 4, 256),\n            nn.ReLU(inplace=True),\n            nn.Linear(256, num_classes),\n        )\n\n    def forward(self, x):\n        x = self.features(x)\n        x = self.classifier(x)\n        return x\n\nmodel = SmallVGG()\nprint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSmallVGG(\n  (features): Sequential(\n    (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (1): ReLU(inplace=True)\n    (2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (3): ReLU(inplace=True)\n    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n    (5): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (6): ReLU(inplace=True)\n    (7): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (8): ReLU(inplace=True)\n    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n    (10): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (11): ReLU(inplace=True)\n    (12): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (13): ReLU(inplace=True)\n    (14): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n  )\n  (classifier): Sequential(\n    (0): Flatten(start_dim=1, end_dim=-1)\n    (1): Linear(in_features=2048, out_features=256, bias=True)\n    (2): ReLU(inplace=True)\n    (3): Linear(in_features=256, out_features=10, bias=True)\n  )\n)\n```\n:::\n:::\n\n\n### 3.4 Verifying the Parameter Count\n\n::: {#2b9251af .cell execution_count=9}\n``` {.python .cell-code}\ntotal = sum(p.numel() for p in model.parameters() if p.requires_grad)\nprint(f\"Hand-computed total: 814,122\")\nprint(f\"PyTorch total      : {total:,}\")\nprint(f\"Match              : {total == 814122}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHand-computed total: 814,122\nPyTorch total      : 814,122\nMatch              : True\n```\n:::\n:::\n\n\n**Expected output:**\n\n```\nHand-computed total: 814,122\nPyTorch total      : 814,122\nMatch              : True\n```\n\n### 3.5 Per-Layer Breakdown\n\nFor deeper analysis it helps to print the count at every layer along with the running total:\n\n::: {#4a6cd7ee .cell execution_count=10}\n``` {.python .cell-code}\ndef layer_summary(model, input_shape):\n    x = torch.randn(*input_shape)\n    print(f\"{'Layer':<35}{'Output Shape':<22}{'Params':>12}\")\n    running = 0\n    for name, layer in model.named_modules():\n        # Skip container modules (Sequential, the model itself)\n        if len(list(layer.children())) > 0:\n            continue\n        try:\n            x = layer(x)\n        except Exception:\n            continue\n        n_params = sum(p.numel() for p in layer.parameters(recurse=False))\n        running += n_params\n        if n_params > 0 or \"Pool\" in layer.__class__.__name__:\n            print(f\"{name:<35}{str(tuple(x.shape)):<22}{n_params:>12,}\")\n    print(f\"{'Total':<35}{'':<22}{running:>12,}\")\n\nlayer_summary(model, input_shape=(1, 3, 32, 32))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLayer                              Output Shape                Params\nfeatures.0                         (1, 32, 32, 32)                896\nfeatures.2                         (1, 32, 32, 32)              9,248\nfeatures.4                         (1, 32, 16, 16)                  0\nfeatures.5                         (1, 64, 16, 16)             18,496\nfeatures.7                         (1, 64, 16, 16)             36,928\nfeatures.9                         (1, 64, 8, 8)                    0\nfeatures.10                        (1, 128, 8, 8)              73,856\nfeatures.12                        (1, 128, 8, 8)             147,584\nfeatures.14                        (1, 128, 4, 4)                   0\nclassifier.1                       (1, 256)                   524,544\nclassifier.3                       (1, 10)                      2,570\nTotal                                                         814,122\n```\n:::\n:::\n\n\n::: {.callout-note}\n## The FC Layer Dominates\n\nLook at the breakdown carefully. The single `Linear(2048, 256)` layer accounts for roughly **64%** of the entire model's parameters (524,544 out of 814,122). The six conv layers combined hold only about 287,000 parameters. This is a very common pattern in classical CNNs and is why architectures like ResNet replaced large FC heads with **global average pooling** followed by a single small Linear layer. We will explore that idea in Section 5.\n:::\n\n## 4. Effect of Hyperparameters on Parameter Count\n\nThe conv parameter formula $P = (C_{in} \\cdot K_h \\cdot K_w + 1) \\cdot C_{out}$ has three knobs that affect the count: kernel size, channel count, and (indirectly) stride. Let's quantify each.\n\n### 4.1 Filter Size\n\nDoubling the kernel side roughly **quadruples** the per-filter weight count, because the kernel is 2D. Going from 3×3 to 5×5 changes the multiplier from 9 to 25 (about 2.8x), and 7×7 jumps to 49 (about 5.4x).\n\n::: {#acaaabd9 .cell execution_count=11}\n``` {.python .cell-code}\nkernel_sizes = [1, 3, 5, 7, 9]\ncounts_k = []\nfor k in kernel_sizes:\n    layer = nn.Conv2d(64, 64, kernel_size=k, padding=k // 2)\n    counts_k.append(count_params(layer))\n\nfig, ax = plt.subplots(figsize=(7, 4))\nbars = ax.bar([str(k) for k in kernel_sizes], counts_k,\n              color='steelblue', edgecolor='black')\nfor i, c in enumerate(counts_k):\n    ax.text(i, c, f'{c:,}', ha='center', va='bottom', fontsize=10)\nax.set_xlabel(\"Kernel size\")\nax.set_ylabel(\"Parameters in Conv 64 -> 64\")\nax.set_title(\"Filter Size vs Parameter Count\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](lab05_files/figure-html/cell-12-output-1.png){}\n:::\n:::\n\n\nThis is one reason why modern architectures stack multiple **3×3 convolutions** instead of using a single large kernel. Two stacked 3×3 convs have a receptive field of 5×5 but use only $2 \\cdot 9 = 18$ weight positions per channel pair, compared to 25 for a single 5×5 conv. Three stacked 3×3 convs match a 7×7 receptive field with $3 \\cdot 9 = 27$ weights per channel pair instead of 49.\n\n### 4.2 Channel Count\n\nBoth $C_{in}$ and $C_{out}$ enter the formula linearly, so doubling **both** quadruples the parameter count. This is why deep CNNs widen the channel dimension only gradually, doubling it after each pooling stage:\n\n::: {#4903396a .cell execution_count=12}\n``` {.python .cell-code}\nchannels = [16, 32, 64, 128, 256, 512]\ncounts_c = []\nfor c in channels:\n    # Each layer doubles the channel count from the previous\n    layer = nn.Conv2d(c, 2 * c, kernel_size=3, padding=1)\n    counts_c.append(count_params(layer))\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(channels, counts_c, marker='o', color='tomato', lw=2)\nfor c, n in zip(channels, counts_c):\n    ax.text(c, n, f' {n:,}', va='center', fontsize=9)\nax.set_xlabel(\"Input channels (output is 2x)\")\nax.set_ylabel(\"Parameters in 3x3 Conv\")\nax.set_title(\"Channel Width vs Parameter Count\")\nax.set_xscale('log', base=2)\nax.set_yscale('log')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](lab05_files/figure-html/cell-13-output-1.png){}\n:::\n:::\n\n\nA straight line on a log-log plot indicates a power law. Here the slope is 2, confirming the quadratic relationship between channel width and parameter count.\n\n### 4.3 Stride Has No Effect on Conv Params\n\nStride does **not** change the conv layer parameter count, since the same filter is applied at fewer spatial positions but the filter itself is unchanged. However, stride aggressively shrinks the spatial dimensions, which reduces the size of the flattened feature vector going into the FC head and therefore shrinks the first FC layer dramatically.\n\n::: {#0e05689d .cell execution_count=13}\n``` {.python .cell-code}\n# Same conv layer, different strides — same parameter count\nfor s in [1, 2, 4]:\n    layer = nn.Conv2d(64, 128, kernel_size=3, stride=s, padding=1)\n    x = torch.randn(1, 64, 32, 32)\n    out = layer(x)\n    print(f\"stride={s}: params={count_params(layer):,},  output spatial={tuple(out.shape[2:])}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstride=1: params=73,856,  output spatial=(32, 32)\nstride=2: params=73,856,  output spatial=(16, 16)\nstride=4: params=73,856,  output spatial=(8, 8)\n```\n:::\n:::\n\n\nThe conv parameter count stays the same across strides, but the output spatial size shrinks. The takeaway is more subtle: **how fast you reduce spatial size determines the size of your FC head**. If you keep features at 32×32 all the way through and only flatten at the end, the first Linear layer becomes enormous.\n\n## 5. Where Do Parameters Hide? Conv vs FC\n\nLet's compute the conv-vs-FC parameter split for our `SmallVGG` and contrast it with a \"modern\" variant that replaces the flatten + large Linear with **global average pooling** (GAP).\n\n::: {#338cfcba .cell execution_count=14}\n``` {.python .cell-code}\nclass ModernCNN(nn.Module):\n    \"\"\"Same conv backbone as SmallVGG, but with GAP instead of a large FC layer.\"\"\"\n    def __init__(self, num_classes=10):\n        super().__init__()\n        self.features = SmallVGG().features\n        self.gap = nn.AdaptiveAvgPool2d(1)        # 4x4 -> 1x1, no parameters\n        self.classifier = nn.Linear(128, num_classes)\n\n    def forward(self, x):\n        x = self.features(x)\n        x = self.gap(x).flatten(1)\n        return self.classifier(x)\n\nmodern = ModernCNN()\n\ndef split_params(model):\n    conv_p, fc_p = 0, 0\n    for m in model.modules():\n        if isinstance(m, nn.Conv2d):\n            conv_p += sum(p.numel() for p in m.parameters())\n        elif isinstance(m, nn.Linear):\n            fc_p += sum(p.numel() for p in m.parameters())\n    return conv_p, fc_p\n\nconv_v1, fc_v1 = split_params(model)\nconv_v2, fc_v2 = split_params(modern)\n\nprint(f\"SmallVGG    | Conv: {conv_v1:>9,}  FC: {fc_v1:>9,}  Total: {conv_v1 + fc_v1:>9,}\")\nprint(f\"ModernCNN   | Conv: {conv_v2:>9,}  FC: {fc_v2:>9,}  Total: {conv_v2 + fc_v2:>9,}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSmallVGG    | Conv:   287,008  FC:   527,114  Total:   814,122\nModernCNN   | Conv:   287,008  FC:     1,290  Total:   288,298\n```\n:::\n:::\n\n\nVisualizing the split:\n\n::: {#98adc394 .cell execution_count=15}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.5))\n\nnames  = ['SmallVGG', 'ModernCNN']\nconvs  = [conv_v1, conv_v2]\nfcs    = [fc_v1, fc_v2]\n\naxes[0].bar(names, convs, label='Conv', color='steelblue')\naxes[0].bar(names, fcs, bottom=convs, label='FC', color='tomato')\naxes[0].set_ylabel(\"Parameter count\")\naxes[0].set_title(\"Parameters by Layer Type\")\naxes[0].legend()\n\naxes[1].pie([conv_v1, fc_v1], labels=['Conv', 'FC'],\n            colors=['steelblue', 'tomato'],\n            autopct='%1.1f%%', startangle=90)\naxes[1].set_title(\"SmallVGG Composition\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](lab05_files/figure-html/cell-16-output-1.png){}\n:::\n:::\n\n\n::: {.callout-important}\n## Global Average Pooling Saves Hundreds of Thousands of Parameters\n\nBy replacing the flatten + `Linear(2048, 256)` + `Linear(256, 10)` head with GAP + `Linear(128, 10)`, the modern variant cuts the parameter count by roughly 65%, while typically matching or improving classification accuracy. This trick was popularized by Network-in-Network (Lin et al., 2014) and is now standard practice in ResNet, MobileNet, EfficientNet, and most modern CNNs. The lesson: **think hard before adding a large FC head** to a CNN, because that single layer can dwarf the rest of the network.\n:::\n\n## 6. A Self-Check Exercise\n\nBefore moving on, try predicting the parameter count of the network below by hand. Then run the verification cell.\n\nThe architecture takes a 1×28×28 grayscale input (MNIST size). It applies `Conv 1 -> 8` with kernel 5 and padding 0, followed by 2×2 MaxPool, then `Conv 8 -> 16` with kernel 5 and padding 0, followed by another 2×2 MaxPool. Finally, it flattens the result and passes it through a `Linear` layer to 10 classes.\n\nCompute the spatial sizes step by step using $H_{out} = \\lfloor (H_{in} + 2P - K)/S \\rfloor + 1$. Then apply the conv parameter formula and the linear parameter formula.\n\n```{.python}\n# Your hand-computation here:\n# Conv1 params  = (1 * 5 * 5 + 1) * 8  = ?\n# Conv2 params  = (8 * 5 * 5 + 1) * 16 = ?\n# Spatial: 28 -> 24 (conv1) -> 12 (pool) -> 8 (conv2) -> 4 (pool)\n# Flatten size  = 16 * 4 * 4 = 256\n# Linear params = (256 + 1) * 10 = ?\n# Total = ?\n```\n\nNow verify:\n\n::: {#e1d2d1f8 .cell execution_count=16}\n``` {.python .cell-code}\nclass TinyMNIST(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Conv2d(1, 8, kernel_size=5),\n            nn.ReLU(),\n            nn.MaxPool2d(2),\n            nn.Conv2d(8, 16, kernel_size=5),\n            nn.ReLU(),\n            nn.MaxPool2d(2),\n            nn.Flatten(),\n            nn.Linear(16 * 4 * 4, 10),\n        )\n\n    def forward(self, x):\n        return self.net(x)\n\ntiny = TinyMNIST()\nprint(f\"Total parameters: {count_params(tiny):,}\")\n\n# Sanity check forward pass\nx = torch.randn(1, 1, 28, 28)\nprint(f\"Output shape    : {tuple(tiny(x).shape)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal parameters: 5,994\nOutput shape    : (1, 10)\n```\n:::\n:::\n\n\n**Expected output:**\n\n```\nTotal parameters: 5,994\nOutput shape    : (1, 10)\n```\n\nThe breakdown matches: Conv1 contributes $(1 \\cdot 25 + 1) \\cdot 8 = 208$, Conv2 contributes $(8 \\cdot 25 + 1) \\cdot 16 = 3{,}216$, and the Linear layer contributes $(256 + 1) \\cdot 10 = 2{,}570$. The total is $208 + 3216 + 2570 = 5{,}994$.\n\nIf your hand-computed value did not match, the most common mistakes are forgetting the bias term, using $K$ instead of $K^2$ in the conv formula, or miscounting the spatial size at the flatten point. Recompute the spatial trace step by step and double-check each layer.\n\n## Summary\n\n- The **conv parameter formula** is $P = (C_{in} \\cdot K_h \\cdot K_w + 1) \\cdot C_{out}$. It does not depend on the spatial size of the input. The \"$+1$\" is the bias term per output channel.\n- **Spatial size** changes via $H_{out} = \\lfloor (H_{in} + 2P - K)/S \\rfloor + 1$. With kernel 3 and padding 1 the spatial dimension is preserved, while pooling with kernel 2 and stride 2 halves it.\n- **Pooling layers have zero parameters.** They reduce spatial size but introduce no weights.\n- In a classical CNN with a flatten + large FC head, the **first FC layer typically holds the majority of parameters**. Replacing it with global average pooling can cut model size dramatically without hurting accuracy.\n- **Filter size scales quadratically** with parameter count, while **channel width scales quadratically** when both $C_{in}$ and $C_{out}$ grow together. **Stride does not change conv parameters** but indirectly shrinks the FC head by reducing spatial size.\n\n## References\n\n- LeCun, Y., Bottou, L., Bengio, Y., and Haffner, P. (1998). Gradient-based learning applied to document recognition. *Proceedings of the IEEE*.\n- Simonyan, K., and Zisserman, A. (2015). Very Deep Convolutional Networks for Large-Scale Image Recognition (VGG). *ICLR*.\n- Lin, M., Chen, Q., and Yan, S. (2014). Network in Network. *ICLR*.\n- Goodfellow, I., Bengio, Y., and Courville, A. (2016). *Deep Learning*. MIT Press.\n\n## Further Reading\n\n- [PyTorch `nn.Conv2d` Documentation](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)\n- [CS231n: Convolutional Networks](https://cs231n.github.io/convolutional-networks/)\n- [A guide to convolution arithmetic for deep learning (Dumoulin & Visin)](https://arxiv.org/abs/1603.07285)\n- [torchinfo: Model summary in PyTorch](https://github.com/TylerYep/torchinfo)\n\n",
    "supporting": [
      "lab05_files"
    ],
    "filters": [],
    "includes": {}
  }
}