<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Byungkook Oh">

<title>Lab5-1. CNN Architecture Design &amp; Parameter Counting – Machine Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dd8e0821c47296b3dcb472f524dd5682.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Machine Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../exercises/index.html" aria-current="page"> 
<span class="menu-text">Exercises</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="http://gli.konkuk.ac.kr"> <i class="bi bi-link-45deg" role="img">
</i> 
<span class="menu-text">GLI Lab</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/GLI-Lab/machine-learning-course" title="Machine Learning Course GitHub" class="quarto-navigation-tool px-1" aria-label="Machine Learning Course GitHub"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../exercises/index.html">Exercises</a></li><li class="breadcrumb-item"><a href="../../exercises/lab05/cnn-architecture.html">Lab5. Convolutional NNs</a></li><li class="breadcrumb-item"><a href="../../exercises/lab05/cnn-architecture.html">CNN Architecture</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../exercises/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/environment-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python Environment Setup</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Lab1. Introduction to ML</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab01/python-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python Basics (⭐)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab01/numpy-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Numpy Basics (⭐⭐)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab01/matplotlib-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matplotlib Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab01/pandas-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pandas Basics</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Lab2. Linear Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab02/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab02/logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab02/classification-metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab02/softmax-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Softmax Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Lab3. Multi-Layer Perceptron</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab03/linear-regression-scratch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression (Scratch)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab03/logistic-regression-scratch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic Regression (Scratch)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab03/softmax-regression-scratch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Softmax Regression (Scratch)</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Lab4. Model Selection and Generalization</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab04/mlp-regression-scratch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MLP Regression (Scratch)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab04/mlp-regression-scratch2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MLP Regression-Improved (Scratch)</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Lab5. Convolutional NNs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab05/cnn-architecture.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">CNN Architecture</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Lab6. Recurrent NNs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/lab06/rnn-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RNN Architecture</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#why-count-parameters" id="toc-why-count-parameters" class="nav-link" data-scroll-target="#why-count-parameters">Why Count Parameters?</a></li>
  <li><a href="#convolutional-layer-parameter-count" id="toc-convolutional-layer-parameter-count" class="nav-link" data-scroll-target="#convolutional-layer-parameter-count">Convolutional Layer Parameter Count</a></li>
  <li><a href="#output-spatial-dimensions" id="toc-output-spatial-dimensions" class="nav-link" data-scroll-target="#output-spatial-dimensions">Output Spatial Dimensions</a></li>
  <li><a href="#other-layer-types" id="toc-other-layer-types" class="nav-link" data-scroll-target="#other-layer-types">Other Layer Types</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">0. Setup</a></li>
  <li><a href="#parameters-of-a-single-2d-convolutional-layer" id="toc-parameters-of-a-single-2d-convolutional-layer" class="nav-link" data-scroll-target="#parameters-of-a-single-2d-convolutional-layer">1. Parameters of a Single 2D Convolutional Layer</a>
  <ul class="collapse">
  <li><a href="#hand-computing-a-conv-layer" id="toc-hand-computing-a-conv-layer" class="nav-link" data-scroll-target="#hand-computing-a-conv-layer">1.1 Hand-Computing a Conv Layer</a></li>
  <li><a href="#a-tiny-worked-example-seeing-the-actual-matrices" id="toc-a-tiny-worked-example-seeing-the-actual-matrices" class="nav-link" data-scroll-target="#a-tiny-worked-example-seeing-the-actual-matrices">1.2 A Tiny Worked Example: Seeing the Actual Matrices</a></li>
  <li><a href="#watching-a-convolution-happen-step-by-step" id="toc-watching-a-convolution-happen-step-by-step" class="nav-link" data-scroll-target="#watching-a-convolution-happen-step-by-step">1.3 Watching a Convolution Happen Step by Step</a></li>
  <li><a href="#tracking-output-spatial-size-on-the-original-layer" id="toc-tracking-output-spatial-size-on-the-original-layer" class="nav-link" data-scroll-target="#tracking-output-spatial-size-on-the-original-layer">1.4 Tracking Output Spatial Size on the Original Layer</a></li>
  </ul></li>
  <li><a href="#tracking-spatial-dimensions-through-a-network" id="toc-tracking-spatial-dimensions-through-a-network" class="nav-link" data-scroll-target="#tracking-spatial-dimensions-through-a-network">2. Tracking Spatial Dimensions Through a Network</a></li>
  <li><a href="#designing-a-vgg-style-cnn-for-cifar-10" id="toc-designing-a-vgg-style-cnn-for-cifar-10" class="nav-link" data-scroll-target="#designing-a-vgg-style-cnn-for-cifar-10">3. Designing a VGG-style CNN for CIFAR-10</a>
  <ul class="collapse">
  <li><a href="#architecture-specification" id="toc-architecture-specification" class="nav-link" data-scroll-target="#architecture-specification">3.1 Architecture Specification</a></li>
  <li><a href="#building-the-network-in-pytorch" id="toc-building-the-network-in-pytorch" class="nav-link" data-scroll-target="#building-the-network-in-pytorch">3.2 Building the Network in PyTorch</a></li>
  <li><a href="#inspecting-the-model-with-torchinfo" id="toc-inspecting-the-model-with-torchinfo" class="nav-link" data-scroll-target="#inspecting-the-model-with-torchinfo">3.3 Inspecting the Model with <code>torchinfo</code></a></li>
  </ul></li>
  <li><a href="#training-the-model" id="toc-training-the-model" class="nav-link" data-scroll-target="#training-the-model">4. Training the Model</a>
  <ul class="collapse">
  <li><a href="#loading-cifar-10" id="toc-loading-cifar-10" class="nav-link" data-scroll-target="#loading-cifar-10">4.1 Loading CIFAR-10</a></li>
  <li><a href="#training-loop" id="toc-training-loop" class="nav-link" data-scroll-target="#training-loop">4.2 Training Loop</a></li>
  <li><a href="#visualizing-training-dynamics" id="toc-visualizing-training-dynamics" class="nav-link" data-scroll-target="#visualizing-training-dynamics">4.3 Visualizing Training Dynamics</a></li>
  </ul></li>
  <li><a href="#inference-using-the-trained-model" id="toc-inference-using-the-trained-model" class="nav-link" data-scroll-target="#inference-using-the-trained-model">5. Inference: Using the Trained Model</a>
  <ul class="collapse">
  <li><a href="#predicting-on-a-batch-of-test-images" id="toc-predicting-on-a-batch-of-test-images" class="nav-link" data-scroll-target="#predicting-on-a-batch-of-test-images">5.1 Predicting on a Batch of Test Images</a></li>
  <li><a href="#visualizing-predictions" id="toc-visualizing-predictions" class="nav-link" data-scroll-target="#visualizing-predictions">5.2 Visualizing Predictions</a></li>
  <li><a href="#per-class-accuracy" id="toc-per-class-accuracy" class="nav-link" data-scroll-target="#per-class-accuracy">5.3 Per-Class Accuracy</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading">Further Reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../exercises/index.html">Exercises</a></li><li class="breadcrumb-item"><a href="../../exercises/lab05/cnn-architecture.html">Lab5. Convolutional NNs</a></li><li class="breadcrumb-item"><a href="../../exercises/lab05/cnn-architecture.html">CNN Architecture</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Lab5-1. CNN Architecture Design &amp; Parameter Counting</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Byungkook Oh </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">2026.05.02</p>
    </div>
  </div>
    
  </div>
  


</header>


<p><a href="https://colab.research.google.com/github/GLI-Lab/machine-learning-course/blob/students/exercises/lab05/cnn-parameters.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid"></a></p>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<ul>
<li>Understand the <strong>parameter count formula</strong> for convolutional layers and apply it manually.</li>
<li>Track how <strong>spatial dimensions</strong> (height, width) propagate through a CNN given kernel size, stride, and padding.</li>
<li>Design a complete <strong>CNN architecture</strong> for a small image classification task and predict its total parameter count before running any code.</li>
<li>Verify your hand-computed counts against PyTorch’s <code>model.parameters()</code>.</li>
<li>Analyze how <strong>filter size, channel width, and stride</strong> affect parameter count, and observe where parameters tend to concentrate in a typical CNN.</li>
</ul>
</section>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<section id="why-count-parameters" class="level3">
<h3 class="anchored" data-anchor-id="why-count-parameters">Why Count Parameters?</h3>
<p>The number of trainable parameters in a model determines three practical things at once: how much GPU memory the model occupies, how many FLOPs each forward pass requires, and how much data you need to train it without overfitting. Modern image models range from a few hundred thousand parameters (MobileNet variants) to billions (ViT-22B). Knowing how to estimate this number for any architecture is one of the first instincts a deep learning practitioner develops, because it tells you immediately whether a design is feasible on your hardware budget.</p>
</section>
<section id="convolutional-layer-parameter-count" class="level3">
<h3 class="anchored" data-anchor-id="convolutional-layer-parameter-count">Convolutional Layer Parameter Count</h3>
<p>A 2D convolutional layer is defined by four hyperparameters: the input channel count <span class="math inline">\(C_{in}\)</span>, the output channel count <span class="math inline">\(C_{out}\)</span>, the kernel height <span class="math inline">\(K_h\)</span>, and the kernel width <span class="math inline">\(K_w\)</span>. Each output channel is produced by a separate filter that spans <strong>all</strong> input channels, so a single filter has <span class="math inline">\(C_{in} \times K_h \times K_w\)</span> weights. With <span class="math inline">\(C_{out}\)</span> filters and one bias per filter, the total parameter count is:</p>
<p><span class="math display">\[\text{\#parameters}_{\text{conv}} = (C_{in} \times K_h \times K_w + 1) \times C_{out}\]</span></p>
<p>The “<span class="math inline">\(+1\)</span>” is the bias term per output channel. Note that this count is <strong>independent of the spatial size</strong> of the input. The same conv layer applied to a 32×32 image and to a 224×224 image has exactly the same parameter count, because the same filter is reused at every spatial position. This weight sharing is what makes CNNs so parameter-efficient compared to fully connected networks.</p>
</section>
<section id="output-spatial-dimensions" class="level3">
<h3 class="anchored" data-anchor-id="output-spatial-dimensions">Output Spatial Dimensions</h3>
<p>After convolution with stride <span class="math inline">\(S\)</span> and zero-padding <span class="math inline">\(P\)</span> on each side, the output spatial size is:</p>
<p><span class="math display">\[H_{out} = \left\lfloor \frac{H_{in} + 2P - K_h}{S} \right\rfloor + 1\]</span></p>
<p>The same formula applies to the width. Pooling layers follow the same rule but typically use <span class="math inline">\(K = S = 2\)</span>, which halves the spatial size at each pooling stage.</p>
</section>
<section id="other-layer-types" class="level3">
<h3 class="anchored" data-anchor-id="other-layer-types">Other Layer Types</h3>
<p>Pooling layers (max pool, average pool) have <strong>zero</strong> parameters. They reduce spatial size but do not introduce weights. Batch normalization layers add <span class="math inline">\(2C\)</span> parameters per channel (a scale and a shift), plus running statistics that are not trainable. A fully connected layer with <span class="math inline">\(M\)</span> inputs and <span class="math inline">\(N\)</span> outputs has <span class="math inline">\((M + 1) \times N\)</span> parameters. The location where features are flattened (the transition from the last conv block to the first FC layer) is usually where parameters accumulate, because the input to the FC layer is the entire flattened feature map.</p>
</section>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">0. Setup</h2>
<div id="31715428" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'whitegrid'</span>, font_scale<span class="op">=</span><span class="fl">1.15</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">42</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="parameters-of-a-single-2d-convolutional-layer" class="level2">
<h2 class="anchored" data-anchor-id="parameters-of-a-single-2d-convolutional-layer">1. Parameters of a Single 2D Convolutional Layer</h2>
<section id="hand-computing-a-conv-layer" class="level3">
<h3 class="anchored" data-anchor-id="hand-computing-a-conv-layer">1.1 Hand-Computing a Conv Layer</h3>
<p>Consider a <code>Conv2d</code> layer that takes 3-channel RGB images and outputs 16 feature maps using 3×3 filters:</p>
<div id="560becb1" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>conv1 <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">16</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conv1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))</code></pre>
</div>
</div>
<p>Plugging into the formula with <span class="math inline">\(C_{in}=3\)</span>, <span class="math inline">\(C_{out}=16\)</span>, <span class="math inline">\(K_h = K_w = 3\)</span>:</p>
<p><span class="math display">\[\text{\#parameters} = (3 \times 3 \times 3 + 1) \times 16 = (27 + 1) \times 16 = 28 \times 16 = 448\]</span></p>
<p>Let’s check what PyTorch reports:</p>
<div id="61299a8b" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> count_params(module):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> module.parameters() <span class="cf">if</span> p.requires_grad)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Parameter count: </span><span class="sc">{</span>count_params(conv1)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter count: 448</code></pre>
</div>
</div>
<p>The number 448 matches our hand calculation exactly. We can also inspect the shapes of the weight tensor and bias tensor directly to confirm the number of parameters is correct:</p>
<div id="ca3130f6" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Weight shape: </span><span class="sc">{</span>conv1<span class="sc">.</span>weight<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)  <span class="co"># (out_channels, in_channels, K_h, K_w)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Bias shape  : </span><span class="sc">{</span>conv1<span class="sc">.</span>bias<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)    <span class="co"># (out_channels,)</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Weight count: </span><span class="sc">{</span>conv1<span class="sc">.</span>weight<span class="sc">.</span>numel()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Bias count  : </span><span class="sc">{</span>conv1<span class="sc">.</span>bias<span class="sc">.</span>numel()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total       : </span><span class="sc">{</span>conv1<span class="sc">.</span>weight<span class="sc">.</span>numel() <span class="op">+</span> conv1<span class="sc">.</span>bias<span class="sc">.</span>numel()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Weight shape: torch.Size([16, 3, 3, 3])
Bias shape  : torch.Size([16])
Weight count: 432
Bias count  : 16
Total       : 448</code></pre>
</div>
</div>
<p>The weight tensor has shape <code>(C_out, C_in, K_h, K_w)</code>. This is the canonical layout for 2D convolution weights in PyTorch and makes the multiplication structure explicit: 16 output filters, each 3×3 in size, applied to 3 input channels.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Conv1d, Conv2d, Conv3d: What’s the Difference?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The “2D” in <code>Conv2d</code> refers to the <strong>spatial dimensions the kernel slides over</strong>, not the dimensionality of the weight tensor itself. PyTorch provides three variants for different data shapes:</p>
<p><strong><code>Conv1d</code></strong> is for sequences. The kernel slides along a single axis (typically time). It is used for raw audio waveforms, ECG signals, or 1D sensor readings. Input shape: <code>(batch, channels, length)</code>. Kernel shape: <code>(C_out, C_in, K)</code>. Parameter count: <span class="math inline">\((C_{in} \cdot K + 1) \cdot C_{out}\)</span>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nn.Conv1d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">1</span>, kernel_size<span class="op">=</span><span class="dv">5</span>)            <span class="co"># input: (B, 3, 120)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong><code>Conv2d</code></strong> is for images. The kernel slides along height and width. Used for RGB photos, grayscale medical scans, spectrograms (which are 2D even though the underlying signal is 1D). Input shape: <code>(batch, channels, H, W)</code>. Kernel shape: <code>(C_out, C_in, K_h, K_w)</code>. Parameter count: <span class="math inline">\((C_{in} \cdot K_h \cdot K_w + 1) \cdot C_{out}\)</span>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">1</span>, kernel_size<span class="op">=</span>(<span class="dv">3</span>, <span class="dv">3</span>))       <span class="co"># input: (B, 3, 128, 128)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong><code>Conv3d</code></strong> is for volumes or video. The kernel slides along three spatial axes (or two spatial plus one temporal). Used for CT/MRI volumes and video clips where temporal context matters. Input shape: <code>(batch, channels, D, H, W)</code>. Kernel shape: <code>(C_out, C_in, K_d, K_h, K_w)</code>. Parameter count: <span class="math inline">\((C_{in} \cdot K_d \cdot K_h \cdot K_w + 1) \cdot C_{out}\)</span>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nn.Conv3d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">1</span>, kernel_size<span class="op">=</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>))    <span class="co"># input: (B, 3, 128, 128, 128)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="a-tiny-worked-example-seeing-the-actual-matrices" class="level3">
<h3 class="anchored" data-anchor-id="a-tiny-worked-example-seeing-the-actual-matrices">1.2 A Tiny Worked Example: Seeing the Actual Matrices</h3>
<p>let’s build a much smaller layer <code>Conv2d(in_channels=1, out_channels=2, kernel_size=2)</code>, where Five parameters per filter (four weights plus one bias), and two filters, gives 10 parameters total:</p>
<p><span class="math display">\[\text{\#parameters} = (1 \times 2 \times 2 + 1) \times 2 = 5 \times 2 = 10\]</span>= 10$$</p>
<div id="973edbfe" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tiny_conv <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">1</span>, out_channels<span class="op">=</span><span class="dv">2</span>, kernel_size<span class="op">=</span><span class="dv">2</span>, bias<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># manually initialize the weights and biases to known values instead of relying on random initialization</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    tiny_conv.weight.copy_(torch.tensor([</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        [[[<span class="fl">1.0</span>,  <span class="fl">0.0</span>],</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>          [<span class="fl">0.0</span>, <span class="op">-</span><span class="fl">1.0</span>]]],   <span class="co"># Filter 0</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        [[[<span class="fl">1.0</span>,  <span class="fl">1.0</span>],</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>          [<span class="fl">1.0</span>,  <span class="fl">1.0</span>]]],   <span class="co"># Filter 1</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    ]))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    tiny_conv.bias.copy_(torch.tensor([<span class="fl">0.5</span>, <span class="op">-</span><span class="fl">2.0</span>]))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Weight tensor shape: </span><span class="sc">{</span><span class="bu">tuple</span>(tiny_conv.weight.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Bias tensor shape  : </span><span class="sc">{</span><span class="bu">tuple</span>(tiny_conv.bias.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total parameters   : </span><span class="sc">{</span>count_params(tiny_conv)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Weight tensor shape: (2, 1, 2, 2)
Bias tensor shape  : (2,)
Total parameters   : 10</code></pre>
</div>
</div>
<p>The shape <code>(2, 1, 2, 2)</code> reads as: <strong>2 output filters</strong>, each looking at <strong>1 input channel</strong>, with a <strong>2×2</strong> kernel. Mathematically the two filters and biases are:</p>
<p><span class="math display">\[
W_0 = \begin{bmatrix} 1 &amp; 0 \\ 0 &amp; -1 \end{bmatrix}, \quad b_0 = 0.5
\qquad\qquad
W_1 = \begin{bmatrix} 1 &amp; 1 \\ 1 &amp; 1 \end{bmatrix}, \quad b_1 = -2.0
\]</span></p>
<p>Each filter is a 2×2 matrix of weights and has its own scalar bias. Together that is <span class="math inline">\(4 + 1 = 5\)</span> parameters per filter, and <span class="math inline">\(5 \times 2 = 10\)</span> parameters in the layer, matching our formula exactly.</p>
<div id="317a4e4c" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> tiny_conv.weight.data       <span class="co"># shape (2, 1, 2, 2)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> tiny_conv.bias.data         <span class="co"># shape (2,)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>filter_0 <span class="op">=</span> W[<span class="dv">0</span>, <span class="dv">0</span>]              <span class="co"># the 2x2 kernel of output channel 0</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>filter_1 <span class="op">=</span> W[<span class="dv">1</span>, <span class="dv">0</span>]              <span class="co"># the 2x2 kernel of output channel 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="watching-a-convolution-happen-step-by-step" class="level3">
<h3 class="anchored" data-anchor-id="watching-a-convolution-happen-step-by-step">1.3 Watching a Convolution Happen Step by Step</h3>
<p>Now let’s apply <code>tiny_conv</code> to a small 4×4 input and trace what each output value comes from. We construct an input where the numbers are easy to recognize:</p>
<div id="a3e01346" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>x_tiny <span class="op">=</span> torch.tensor([[[[<span class="fl">1.</span>, <span class="fl">2.</span>, <span class="fl">3.</span>, <span class="fl">4.</span>],</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                         [<span class="fl">5.</span>, <span class="fl">6.</span>, <span class="fl">7.</span>, <span class="fl">8.</span>],</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                         [<span class="fl">9.</span>, <span class="fl">10.</span>, <span class="fl">11.</span>, <span class="fl">12.</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                         [<span class="fl">13.</span>, <span class="fl">14.</span>, <span class="fl">15.</span>, <span class="fl">16.</span>]]]])  <span class="co"># shape (1, 1, 4, 4)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Input shape: </span><span class="sc">{</span><span class="bu">tuple</span>(x_tiny.shape)<span class="sc">}</span><span class="ss">  (batch=1, channels=1, H=4, W=4)"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Input matrix:"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(x_tiny[<span class="dv">0</span>, <span class="dv">0</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Input shape: (1, 1, 4, 4)  (batch=1, channels=1, H=4, W=4)
Input matrix:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])</code></pre>
</div>
</div>
<p><strong>Expected output:</strong></p>
<p><span class="math display">\[
X = \begin{bmatrix} 1 &amp; 2 &amp; 3 &amp; 4 \\ 5 &amp; 6 &amp; 7 &amp; 8 \\ 9 &amp; 10 &amp; 11 &amp; 12 \\ 13 &amp; 14 &amp; 15 &amp; 16 \end{bmatrix}
\]</span></p>
<p>With the input height <span class="math inline">\(H_{in} = 4\)</span> and kernel size <span class="math inline">\(K = 2\)</span> from the layer we just defined, plus the PyTorch defaults <code>padding=0</code> (<span class="math inline">\(P = 0\)</span>) and <code>stride=1</code> (<span class="math inline">\(S = 1\)</span>), the output spatial size formula gives:</p>
<p><span class="math display">\[H_{out} = \left\lfloor \frac{H_{in} + 2P - K}{S} \right\rfloor + 1 = \left\lfloor \frac{4 + 2 \cdot 0 - 2}{1} \right\rfloor + 1 = 2 + 1 = 3\]</span></p>
<p>So the output should be a 3×3 feature map per filter, and there are 2 filters, giving an output shape of <code>(1, 2, 3, 3)</code>.`.</p>
<div id="9d00f102" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>y_tiny <span class="op">=</span> tiny_conv(x_tiny)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Output shape: </span><span class="sc">{</span><span class="bu">tuple</span>(y_tiny.shape)<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Output channel 0 (3x3):"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_tiny[<span class="dv">0</span>, <span class="dv">0</span>].detach())</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Output channel 1 (3x3):"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_tiny[<span class="dv">0</span>, <span class="dv">1</span>].detach())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Output shape: (1, 2, 3, 3)

Output channel 0 (3x3):
tensor([[-4.5000, -4.5000, -4.5000],
        [-4.5000, -4.5000, -4.5000],
        [-4.5000, -4.5000, -4.5000]])

Output channel 1 (3x3):
tensor([[12., 16., 20.],
        [28., 32., 36.],
        [44., 48., 52.]])</code></pre>
</div>
</div>
<p><strong>Expected output:</strong></p>
<p>For output channel 0, every 2×2 patch contributes <span class="math inline">\(x_{\text{TL}} - x_{\text{BR}} + 0.5\)</span> (top-left minus bottom-right, plus bias). Since the input increases by exactly 5 along the anti-diagonal of every patch, every value comes out to <span class="math inline">\(-5 + 0.5 = -4.5\)</span>:</p>
<p><span class="math display">\[
Y_0 = \begin{bmatrix} -4.5 &amp; -4.5 &amp; -4.5 \\ -4.5 &amp; -4.5 &amp; -4.5 \\ -4.5 &amp; -4.5 &amp; -4.5 \end{bmatrix}
\]</span></p>
<p>For output channel 1, each value is the sum of four input values minus 2:</p>
<p><span class="math display">\[
Y_1 = \begin{bmatrix} 12 &amp; 16 &amp; 20 \\ 28 &amp; 32 &amp; 36 \\ 44 &amp; 48 &amp; 52 \end{bmatrix}
\]</span></p>
<p>This is what <code>Conv2d</code> is doing under the hood for every output position and every output channel: a tiny weighted sum (the element-wise product of filter and patch, summed up), plus the bias, repeated across spatial positions and across filters.</p>
</section>
<section id="tracking-output-spatial-size-on-the-original-layer" class="level3">
<h3 class="anchored" data-anchor-id="tracking-output-spatial-size-on-the-original-layer">1.4 Tracking Output Spatial Size on the Original Layer</h3>
<p>Now back to the original <code>conv1</code>, which uses kernel size <span class="math inline">\(K = 3\)</span> with <code>padding=1</code>. Let’s pass a dummy 32×32 RGB image through it and confirm the output size matches the formula. With the input height <span class="math inline">\(H_{in} = 32\)</span>, kernel <span class="math inline">\(K = 3\)</span>, padding <span class="math inline">\(P = 1\)</span>, and the default stride <span class="math inline">\(S = 1\)</span>:</p>
<p><span class="math display">\[H_{out} = \left\lfloor \frac{H_{in} + 2P - K}{S} \right\rfloor + 1 = \left\lfloor \frac{32 + 2 \cdot 1 - 3}{1} \right\rfloor + 1 = 31 + 1 = 32\]</span></p>
<p>Padding of 1 with kernel size 3 and stride 1 preserves the spatial dimension. This is the most common configuration in modern CNNs.</p>
<div id="1f60d135" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">32</span>, <span class="dv">32</span>)  <span class="co"># (batch, channels, H, W)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> conv1(x)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Input  shape: </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Output shape: </span><span class="sc">{</span><span class="bu">tuple</span>(out.shape)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Input  shape: (1, 3, 32, 32)
Output shape: (1, 16, 32, 32)</code></pre>
</div>
</div>
<p>The spatial dimensions stay at 32×32 as predicted, while the channel count changes from 3 to 16 because <code>conv1</code> was defined with <code>out_channels=16</code>.</p>
</section>
</section>
<section id="tracking-spatial-dimensions-through-a-network" class="level2">
<h2 class="anchored" data-anchor-id="tracking-spatial-dimensions-through-a-network">2. Tracking Spatial Dimensions Through a Network</h2>
<p>In a CNN the spatial size and channel count change at every layer. The pattern in most practical architectures is the same: spatial size shrinks (via pooling or strided conv) while channel count grows. This trades resolution for richer feature representations.</p>
<p>To inspect this layer by layer, we use <a href="https://github.com/TylerYep/torchinfo"><strong>torchinfo</strong></a>, the standard tool for summarizing any <code>nn.Module</code>. It prints per-layer output shapes, parameter counts, and total memory usage in one formatted table.</p>
<p>Let’s wrap a small block (conv, pool, conv, pool) into an <code>nn.Sequential</code> and pass it to <code>summary</code> along with the input shape:</p>
<div id="eab49183" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># torchinfo is not part of the standard PyTorch installation.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Uncomment the next line if you are running this for the first time on a fresh environment.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># !pip install torchinfo</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torchinfo <span class="im">import</span> summary</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>small_block <span class="op">=</span> nn.Sequential(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">3</span>, <span class="dv">16</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">16</span>, <span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>summary(small_block, input_size<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">32</span>, <span class="dv">32</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Sequential                               [1, 32, 8, 8]             --
├─Conv2d: 1-1                            [1, 16, 32, 32]           448
├─MaxPool2d: 1-2                         [1, 16, 16, 16]           --
├─Conv2d: 1-3                            [1, 32, 16, 16]           4,640
├─MaxPool2d: 1-4                         [1, 32, 8, 8]             --
==========================================================================================
Total params: 5,088
Trainable params: 5,088
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 1.65
==========================================================================================
Input size (MB): 0.01
Forward/backward pass size (MB): 0.20
Params size (MB): 0.02
Estimated Total Size (MB): 0.23
==========================================================================================</code></pre>
</div>
</div>
<p>The output is divided into three sections: a per-layer table, a parameter summary, and a memory estimate.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading the Per-Layer Table
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Sequential                               [1, 32, 8, 8]             --
├─Conv2d: 1-1                            [1, 16, 32, 32]           448
├─MaxPool2d: 1-2                         [1, 16, 16, 16]           --
├─Conv2d: 1-3                            [1, 32, 16, 16]           4,640
├─MaxPool2d: 1-4                         [1, 32, 8, 8]             --</code></pre>
<ul>
<li><strong><code>Layer (type:depth-idx)</code></strong> shows the module hierarchy. The index <code>1-1</code>, <code>1-2</code>, … encodes depth and order within the module tree. For nested architectures like ResNet, this column makes the tree structure immediately readable.</li>
<li><strong><code>Output Shape</code></strong> is the tensor shape <strong>after</strong> that layer runs, in <code>[batch, channels, H, W]</code> format. Following this column top to bottom shows how the input is transformed: channels go 3 → 16 → 32 while spatial size shrinks 32 → 16 → 8.</li>
<li><strong><code>Param #</code></strong> is the number of trainable parameters owned by that layer alone. The <code>--</code> for <code>MaxPool2d</code> means <strong>zero parameters</strong>, and the <code>Sequential</code> row is also <code>--</code> because containers hold no weights, only their children do.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading the Parameter Summary
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Total params: 5,088
Trainable params: 5,088
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 1.65</code></pre>
<ul>
<li><strong><code>Total params</code></strong> is the simple sum of the <code>Param #</code> column (<span class="math inline">\(448 + 4{,}640 = 5{,}088\)</span>).</li>
<li><strong><code>Trainable params</code> vs <code>Non-trainable params</code></strong> splits the total by <code>requires_grad</code>. This matters in <strong>transfer learning</strong>: when freezing a pretrained backbone and fine-tuning only the classifier, the backbone’s parameters move to the non-trainable side. The easiest sanity check that your freezing is set up correctly.</li>
<li><strong><code>Total mult-adds (Units.MEGABYTES)</code></strong> is the number of <strong>multiply-accumulate (MAC) operations</strong> per forward pass. The “MEGABYTES” label is misleading: this is actually millions of MACs (MMACs). One MAC ≈ two FLOPs, so 1.65 MMACs ≈ 3.3 MFLOPs. This is the standard way to compare computational cost across architectures.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading the Memory Estimate assuming float32 (4 bytes per number)
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Input size (MB): 0.01
Forward/backward pass size (MB): 0.20
Params size (MB): 0.02
Estimated Total Size (MB): 0.23</code></pre>
<ul>
<li><strong><code>Input size</code></strong> is the memory of the input tensor: <span class="math inline">\(1 \cdot 3 \cdot 32 \cdot 32 \cdot 4 \text{ bytes} \approx 0.012\)</span> MB.</li>
<li><strong><code>Forward/backward pass size</code></strong> is the memory of all <strong>intermediate activations</strong> retained for the backward pass. This grows fastest as networks deepen and is the most common cause of CUDA out-of-memory errors.</li>
<li><strong><code>Params size</code></strong> is the memory of the weights themselves: <span class="math inline">\(5{,}088 \cdot 4 \text{ bytes} \approx 0.02\)</span> MB.</li>
<li><strong><code>Estimated Total Size</code></strong> is the sum of the three. It estimates <strong>inference memory only</strong>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Why “Estimated” Is Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Real training adds three memory consumers that <code>summary</code> does not report:</p>
<ol type="1">
<li><strong>Gradient buffers</strong>, one per trainable parameter, roughly the same size as <code>Params size</code>.</li>
<li><strong>Optimizer state</strong>: Adam stores momentum and variance per parameter, adding 2× to 3× <code>Params size</code> on top.</li>
<li><strong>CUDA workspace</strong>: cuDNN allocates temporary buffers for fast convolution, often hundreds of MB.</li>
</ol>
<p>Rule of thumb: <strong>actual training memory is 3–5× the <code>Estimated Total Size</code></strong>.</p>
</div>
</div>
</section>
<section id="designing-a-vgg-style-cnn-for-cifar-10" class="level2">
<h2 class="anchored" data-anchor-id="designing-a-vgg-style-cnn-for-cifar-10">3. Designing a VGG-style CNN for CIFAR-10</h2>
<p>Our task: build a CNN classifier for CIFAR-10. Input images are 32×32 RGB and there are 10 output classes (airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck). We will use a “VGG-style” architecture, which stacks repeated <code>[Conv -&gt; ReLU -&gt; Conv -&gt; ReLU -&gt; MaxPool]</code> blocks followed by a small fully connected head.</p>
<section id="architecture-specification" class="level3">
<h3 class="anchored" data-anchor-id="architecture-specification">3.1 Architecture Specification</h3>
<p>The network has three convolutional blocks followed by a fully connected head:</p>
<ul>
<li><strong>Block 1</strong>: <code>Conv 3 -&gt; 32</code> and <code>Conv 32 -&gt; 32</code>, then <code>MaxPool</code> (32×32 -&gt; 16×16).</li>
<li><strong>Block 2</strong>: <code>Conv 32 -&gt; 64</code> and <code>Conv 64 -&gt; 64</code>, then <code>MaxPool</code> (16×16 -&gt; 8×8).</li>
<li><strong>Block 3</strong>: <code>Conv 64 -&gt; 128</code> and <code>Conv 128 -&gt; 128</code>, then <code>MaxPool</code> (8×8 -&gt; 4×4).</li>
<li><strong>Head</strong>: <code>Flatten -&gt; Linear 2048 -&gt; 256 -&gt; Linear 256 -&gt; 10</code>.</li>
</ul>
<p>All conv layers use 3×3 kernels with padding 1 (so spatial size is preserved within each block), and all pooling is 2×2 with stride 2 (so spatial size halves at each block boundary).</p>
</section>
<section id="building-the-network-in-pytorch" class="level3">
<h3 class="anchored" data-anchor-id="building-the-network-in-pytorch">3.2 Building the Network in PyTorch</h3>
<div id="0b9eaf0b" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SmallVGG(nn.Module):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, num_classes<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.features <span class="op">=</span> nn.Sequential(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Block 1</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">3</span>, <span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">32</span>, <span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>            nn.MaxPool2d(<span class="dv">2</span>),                              <span class="co"># 32x32 -&gt; 16x16</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Block 2</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">32</span>, <span class="dv">64</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">64</span>, <span class="dv">64</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>            nn.MaxPool2d(<span class="dv">2</span>),                              <span class="co"># 16x16 -&gt; 8x8</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Block 3</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">64</span>, <span class="dv">128</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">128</span>, <span class="dv">128</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>            nn.MaxPool2d(<span class="dv">2</span>),                              <span class="co"># 8x8 -&gt; 4x4</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.classifier <span class="op">=</span> nn.Sequential(</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>            nn.Flatten(),</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>            nn.Linear(<span class="dv">128</span> <span class="op">*</span> <span class="dv">4</span> <span class="op">*</span> <span class="dv">4</span>, <span class="dv">256</span>),</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(inplace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>            nn.Linear(<span class="dv">256</span>, num_classes),</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.features(x)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.classifier(x)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SmallVGG()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="inspecting-the-model-with-torchinfo" class="level3">
<h3 class="anchored" data-anchor-id="inspecting-the-model-with-torchinfo">3.3 Inspecting the Model with <code>torchinfo</code></h3>
<p>Before training, let’s confirm the architecture works as designed by inspecting it with <code>torchinfo</code>:</p>
<div id="721c8c09" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>summary(model, input_size<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">32</span>, <span class="dv">32</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
SmallVGG                                 [1, 10]                   --
├─Sequential: 1-1                        [1, 128, 4, 4]            --
│    └─Conv2d: 2-1                       [1, 32, 32, 32]           896
│    └─ReLU: 2-2                         [1, 32, 32, 32]           --
│    └─Conv2d: 2-3                       [1, 32, 32, 32]           9,248
│    └─ReLU: 2-4                         [1, 32, 32, 32]           --
│    └─MaxPool2d: 2-5                    [1, 32, 16, 16]           --
│    └─Conv2d: 2-6                       [1, 64, 16, 16]           18,496
│    └─ReLU: 2-7                         [1, 64, 16, 16]           --
│    └─Conv2d: 2-8                       [1, 64, 16, 16]           36,928
│    └─ReLU: 2-9                         [1, 64, 16, 16]           --
│    └─MaxPool2d: 2-10                   [1, 64, 8, 8]             --
│    └─Conv2d: 2-11                      [1, 128, 8, 8]            73,856
│    └─ReLU: 2-12                        [1, 128, 8, 8]            --
│    └─Conv2d: 2-13                      [1, 128, 8, 8]            147,584
│    └─ReLU: 2-14                        [1, 128, 8, 8]            --
│    └─MaxPool2d: 2-15                   [1, 128, 4, 4]            --
├─Sequential: 1-2                        [1, 10]                   --
│    └─Flatten: 2-16                     [1, 2048]                 --
│    └─Linear: 2-17                      [1, 256]                  524,544
│    └─ReLU: 2-18                        [1, 256]                  --
│    └─Linear: 2-19                      [1, 10]                   2,570
==========================================================================================
Total params: 814,122
Trainable params: 814,122
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 39.28
==========================================================================================
Input size (MB): 0.01
Forward/backward pass size (MB): 0.92
Params size (MB): 3.26
Estimated Total Size (MB): 4.19
==========================================================================================</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where Do the Parameters Concentrate?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Scanning the <code>Param #</code> column reveals the most important fact about classical CNN architectures: <strong>the first FC layer dominates</strong>. The single <code>Linear(2048, 256)</code> accounts for 524,544 parameters, roughly <strong>64%</strong> of the entire model’s 814,122. The six conv layers combined hold only about 287,000.</p>
<p>This happens because the FC layer must connect every flattened spatial location to every hidden unit: <span class="math inline">\(2048 \times 256 + 256 = 524{,}544\)</span>. Modern architectures (ResNet, MobileNet, EfficientNet) avoid this by replacing flatten + large FC with <strong>global average pooling</strong>, which collapses each feature map to a single value before the final classifier. We will not implement that here, but it is the single most impactful design choice in modern CNNs.</p>
</div>
</div>
</section>
</section>
<section id="training-the-model" class="level2">
<h2 class="anchored" data-anchor-id="training-the-model">4. Training the Model</h2>
<p>With the architecture verified, we now train the model on CIFAR-10.</p>
<section id="loading-cifar-10" class="level3">
<h3 class="anchored" data-anchor-id="loading-cifar-10">4.1 Loading CIFAR-10</h3>
<p>We use HuggingFace’s <code>datasets</code> library to download CIFAR-10. It is more reliable than <code>torchvision.datasets.CIFAR10</code>, which sometimes fails with HTTP errors due to mirror availability. We then wrap the HuggingFace dataset in a small PyTorch <code>Dataset</code> class so it works with the standard <code>DataLoader</code>.</p>
<div id="d8183086" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install if needed (uncomment on first run):</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># !pip install datasets</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.optim <span class="im">as</span> optim</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.utils.data <span class="im">import</span> Dataset, DataLoader</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torchvision <span class="im">import</span> transforms</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datasets <span class="im">import</span> load_dataset</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>device <span class="op">=</span> torch.device(<span class="st">"cuda"</span> <span class="cf">if</span> torch.cuda.is_available() <span class="cf">else</span> <span class="st">"cpu"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training on: </span><span class="sc">{</span>device<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Load CIFAR-10 from HuggingFace Hub</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>hf_dataset <span class="op">=</span> load_dataset(<span class="st">"uoft-cs/cifar10"</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hf_dataset)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/home/bkoh/Developer/course/machine-learning-course/.pixi/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning:

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Training on: cuda</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>DatasetDict({
    train: Dataset({
        features: ['img', 'label'],
        num_rows: 50000
    })
    test: Dataset({
        features: ['img', 'label'],
        num_rows: 10000
    })
})</code></pre>
</div>
</div>
<p><strong>Expected output:</strong></p>
<pre><code>DatasetDict({
    train: Dataset({
        features: ['img', 'label'],
        num_rows: 50000
    })
    test: Dataset({
        features: ['img', 'label'],
        num_rows: 10000
    })
})</code></pre>
<p>Each row of the dataset has two fields: <code>img</code> (a PIL image of shape 32×32×3) and <code>label</code> (an integer class index from 0 to 9). We now wrap this in a thin PyTorch <code>Dataset</code> that applies the standard CIFAR-10 normalization on the fly:</p>
<div id="ffd7b33d" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CIFAR-10 channel means and stds (well-known constants for this dataset)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>CIFAR_MEAN <span class="op">=</span> (<span class="fl">0.4914</span>, <span class="fl">0.4822</span>, <span class="fl">0.4465</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>CIFAR_STD  <span class="op">=</span> (<span class="fl">0.2470</span>, <span class="fl">0.2435</span>, <span class="fl">0.2616</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>transform <span class="op">=</span> transforms.Compose([</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    transforms.ToTensor(),                          <span class="co"># PIL -&gt; Tensor in [0, 1]</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),    <span class="co"># zero mean, unit variance per channel</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CIFAR10HF(Dataset):</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Wraps a HuggingFace CIFAR-10 split as a PyTorch Dataset."""</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, hf_split, transform<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.data <span class="op">=</span> hf_split</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.transform <span class="op">=</span> transform</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__len__</span>(<span class="va">self</span>):</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">len</span>(<span class="va">self</span>.data)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__getitem__</span>(<span class="va">self</span>, idx):</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>        row <span class="op">=</span> <span class="va">self</span>.data[idx]</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>        img, label <span class="op">=</span> row[<span class="st">"img"</span>], row[<span class="st">"label"</span>]</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.transform <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>            img <span class="op">=</span> <span class="va">self</span>.transform(img)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> img, label</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>train_set <span class="op">=</span> CIFAR10HF(hf_dataset[<span class="st">"train"</span>], transform<span class="op">=</span>transform)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>test_set  <span class="op">=</span> CIFAR10HF(hf_dataset[<span class="st">"test"</span>],  transform<span class="op">=</span>transform)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>train_loader <span class="op">=</span> DataLoader(train_set, batch_size<span class="op">=</span><span class="dv">128</span>, shuffle<span class="op">=</span><span class="va">True</span>,  num_workers<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>test_loader  <span class="op">=</span> DataLoader(test_set,  batch_size<span class="op">=</span><span class="dv">256</span>, shuffle<span class="op">=</span><span class="va">False</span>, num_workers<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>CLASSES <span class="op">=</span> (<span class="st">'airplane'</span>, <span class="st">'automobile'</span>, <span class="st">'bird'</span>, <span class="st">'cat'</span>, <span class="st">'deer'</span>,</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>           <span class="st">'dog'</span>, <span class="st">'frog'</span>, <span class="st">'horse'</span>, <span class="st">'ship'</span>, <span class="st">'truck'</span>)</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Train images: </span><span class="sc">{</span><span class="bu">len</span>(train_set)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test images : </span><span class="sc">{</span><span class="bu">len</span>(test_set)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity check: peek at one sample</span></span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>img, label <span class="op">=</span> train_set[<span class="dv">0</span>]</span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Sample tensor shape: </span><span class="sc">{</span><span class="bu">tuple</span>(img.shape)<span class="sc">}</span><span class="ss">, label: </span><span class="sc">{</span>CLASSES[label]<span class="sc">}</span><span class="ss"> (idx </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train images: 50,000
Test images : 10,000

Sample tensor shape: (3, 32, 32), label: airplane (idx 0)</code></pre>
</div>
</div>
<p><strong>Expected output:</strong></p>
<pre><code>Train images: 50,000
Test images : 10,000

Sample tensor shape: (3, 32, 32), label: frog (idx 6)</code></pre>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Normalize?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Without normalization the input pixel values are roughly in <span class="math inline">\([0, 1]\)</span> after <code>ToTensor</code>, but the three color channels have different means (red is brighter on average than blue in CIFAR-10). Normalization shifts each channel to zero mean and unit variance, which keeps gradients well-scaled across channels and typically improves convergence speed by 2 to 3×.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why Wrap the HuggingFace Dataset?
</div>
</div>
<div class="callout-body-container callout-body">
<p>HuggingFace’s <code>datasets</code> returns rows as Python dictionaries, while PyTorch’s <code>DataLoader</code> expects items as tuples (or other tensor-friendly structures). The thin <code>CIFAR10HF</code> wrapper just translates <code>{"img": ..., "label": ...}</code> into <code>(img_tensor, label_int)</code> and applies the transform. This pattern (a tiny <code>Dataset</code> class adapting an external data source) is the cleanest way to bridge HuggingFace and PyTorch.</p>
</div>
</div>
</section>
<section id="training-loop" class="level3">
<h3 class="anchored" data-anchor-id="training-loop">4.2 Training Loop</h3>
<p>We train with <strong>cross-entropy loss</strong> and the <strong>Adam optimizer</strong>. Adam is a good default for image classification because it adapts the learning rate per parameter, removing some of the manual tuning that plain SGD requires.</p>
<div id="1fd7dfe9" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SmallVGG().to(device)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.CrossEntropyLoss()</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> optim.Adam(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>EPOCHS <span class="op">=</span> <span class="dv">5</span>  <span class="co"># increase to 15-20 for higher accuracy</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>train_losses, train_accs <span class="op">=</span> [], []</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>test_losses,  test_accs  <span class="op">=</span> [], []</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, EPOCHS <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- Training pass ---</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    model.train()</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    running_loss, correct, total <span class="op">=</span> <span class="fl">0.0</span>, <span class="dv">0</span>, <span class="dv">0</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x, y <span class="kw">in</span> train_loader:</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>        x, y <span class="op">=</span> x.to(device), y.to(device)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> model(x)</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> criterion(logits, y)</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>        running_loss <span class="op">+=</span> loss.item() <span class="op">*</span> x.size(<span class="dv">0</span>)</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>        correct      <span class="op">+=</span> (logits.argmax(dim<span class="op">=</span><span class="dv">1</span>) <span class="op">==</span> y).<span class="bu">sum</span>().item()</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>        total        <span class="op">+=</span> x.size(<span class="dv">0</span>)</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>    train_losses.append(running_loss <span class="op">/</span> total)</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>    train_accs.append(correct <span class="op">/</span> total)</span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- Evaluation pass ---</span></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>    running_loss, correct, total <span class="op">=</span> <span class="fl">0.0</span>, <span class="dv">0</span>, <span class="dv">0</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> x, y <span class="kw">in</span> test_loader:</span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>            x, y <span class="op">=</span> x.to(device), y.to(device)</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>            logits <span class="op">=</span> model(x)</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> criterion(logits, y)</span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>            running_loss <span class="op">+=</span> loss.item() <span class="op">*</span> x.size(<span class="dv">0</span>)</span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>            correct      <span class="op">+=</span> (logits.argmax(dim<span class="op">=</span><span class="dv">1</span>) <span class="op">==</span> y).<span class="bu">sum</span>().item()</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>            total        <span class="op">+=</span> x.size(<span class="dv">0</span>)</span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>    test_losses.append(running_loss <span class="op">/</span> total)</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a>    test_accs.append(correct <span class="op">/</span> total)</span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Epoch </span><span class="sc">{</span>epoch<span class="sc">:2d}</span><span class="ss"> | "</span></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"train loss </span><span class="sc">{</span>train_losses[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">, acc </span><span class="sc">{</span>train_accs[<span class="op">-</span><span class="dv">1</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:5.2f}</span><span class="ss">% | "</span></span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"test loss </span><span class="sc">{</span>test_losses[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">, acc </span><span class="sc">{</span>test_accs[<span class="op">-</span><span class="dv">1</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:5.2f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch  1 | train loss 1.5647, acc 42.06% | test loss 1.2376, acc 55.14%
Epoch  2 | train loss 1.0875, acc 61.02% | test loss 0.9865, acc 64.79%
Epoch  3 | train loss 0.8390, acc 70.45% | test loss 0.8186, acc 71.14%
Epoch  4 | train loss 0.6781, acc 76.15% | test loss 0.7809, acc 73.46%
Epoch  5 | train loss 0.5689, acc 79.89% | test loss 0.6878, acc 76.49%</code></pre>
</div>
</div>
<p>A randomly initialized model would achieve 10% test accuracy on CIFAR-10 (random guessing among 10 classes). After 5 epochs <code>SmallVGG</code> reaches roughly 70%, which is decent for a sub-million-parameter network without data augmentation. Training for 15 to 20 epochs typically pushes test accuracy above 80%.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>On a CPU, Reduce the Epoch Count
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are running this notebook on a CPU rather than a GPU, 5 epochs of CIFAR-10 may take 10 to 20 minutes. Reduce <code>EPOCHS = 1</code> and <code>batch_size=64</code> for a quick smoke test, or run the notebook in Google Colab with a free GPU runtime to see real training dynamics.</p>
</div>
</div>
</section>
<section id="visualizing-training-dynamics" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-training-dynamics">4.3 Visualizing Training Dynamics</h3>
<p>The numbers above tell us training is working, but the curves tell us <strong>how</strong> it is working: are we still improving, or have we plateaued? Are we overfitting?</p>
<div id="536a2678" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>epochs_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, EPOCHS <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(epochs_range, train_losses, marker<span class="op">=</span><span class="st">'o'</span>, label<span class="op">=</span><span class="st">'Train'</span>, color<span class="op">=</span><span class="st">'steelblue'</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(epochs_range, test_losses,  marker<span class="op">=</span><span class="st">'s'</span>, label<span class="op">=</span><span class="st">'Test'</span>,  color<span class="op">=</span><span class="st">'tomato'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Loss per Epoch"</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Epoch"</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Cross-entropy loss"</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(epochs_range, [a <span class="op">*</span> <span class="dv">100</span> <span class="cf">for</span> a <span class="kw">in</span> train_accs], marker<span class="op">=</span><span class="st">'o'</span>, label<span class="op">=</span><span class="st">'Train'</span>, color<span class="op">=</span><span class="st">'steelblue'</span>)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(epochs_range, [a <span class="op">*</span> <span class="dv">100</span> <span class="cf">for</span> a <span class="kw">in</span> test_accs],  marker<span class="op">=</span><span class="st">'s'</span>, label<span class="op">=</span><span class="st">'Test'</span>,  color<span class="op">=</span><span class="st">'tomato'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Accuracy per Epoch"</span>)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Epoch"</span>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"Accuracy (%)"</span>)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="cnn-architecture_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The training loss continues to decrease while the test loss starts to flatten. The growing gap between train and test accuracy is the signature of mild overfitting, which is expected for a model trained without data augmentation or regularization.</p>
</section>
</section>
<section id="inference-using-the-trained-model" class="level2">
<h2 class="anchored" data-anchor-id="inference-using-the-trained-model">5. Inference: Using the Trained Model</h2>
<p>Training is only half the story. Now we use the model to make predictions on new images and inspect what it actually got right and wrong.</p>
<section id="predicting-on-a-batch-of-test-images" class="level3">
<h3 class="anchored" data-anchor-id="predicting-on-a-batch-of-test-images">5.1 Predicting on a Batch of Test Images</h3>
<div id="b32153e3" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get one batch from the test loader</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>data_iter <span class="op">=</span> <span class="bu">iter</span>(test_loader)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>images, labels <span class="op">=</span> <span class="bu">next</span>(data_iter)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>images, labels <span class="op">=</span> images.to(device), labels.to(device)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Forward pass with no_grad: we are not training</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>model.<span class="bu">eval</span>()</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    logits <span class="op">=</span> model(images)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    probs  <span class="op">=</span> torch.softmax(logits, dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    preds  <span class="op">=</span> probs.argmax(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>    confidence <span class="op">=</span> probs.<span class="bu">max</span>(dim<span class="op">=</span><span class="dv">1</span>).values</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print first 8 predictions</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Idx'</span><span class="sc">:&lt;5}{</span><span class="st">'True'</span><span class="sc">:&lt;14}{</span><span class="st">'Predicted'</span><span class="sc">:&lt;14}{</span><span class="st">'Confidence'</span><span class="sc">:&lt;12}{</span><span class="st">'Correct'</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>):</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>    correct <span class="op">=</span> <span class="st">"✓"</span> <span class="cf">if</span> preds[i] <span class="op">==</span> labels[i] <span class="cf">else</span> <span class="st">"✗"</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">:&lt;5}{</span>CLASSES[labels[i]]<span class="sc">:&lt;14}{</span>CLASSES[preds[i]]<span class="sc">:&lt;14}</span><span class="ss">"</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>confidence[i]<span class="sc">.</span>item()<span class="op">*</span><span class="dv">100</span><span class="sc">:&gt;6.1f}</span><span class="ss">%      </span><span class="sc">{</span>correct<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Idx  True          Predicted     Confidence  Correct
0    cat           cat             89.7%      ✓
1    ship          ship            89.6%      ✓
2    ship          ship            96.2%      ✓
3    airplane      airplane        89.9%      ✓
4    frog          frog            86.1%      ✓
5    frog          frog            89.9%      ✓
6    automobile    automobile      77.8%      ✓
7    frog          deer            59.6%      ✗</code></pre>
</div>
</div>
<p><code>softmax</code> converts the raw logits into probabilities that sum to 1 across the 10 classes. <code>argmax(dim=1)</code> then picks the most likely class. Confidence is just the probability the model assigned to that winning class.</p>
</section>
<section id="visualizing-predictions" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-predictions">5.2 Visualizing Predictions</h3>
<p>Numbers in a table are easy to skim past. Showing the actual images alongside the model’s verdict makes failure modes much more concrete:</p>
<div id="3305d1e2" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> denormalize(tensor):</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Reverse the normalization so we can display the image."""</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    mean <span class="op">=</span> torch.tensor(CIFAR_MEAN).view(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>).to(tensor.device)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    std  <span class="op">=</span> torch.tensor(CIFAR_STD).view(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>).to(tensor.device)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (tensor <span class="op">*</span> std <span class="op">+</span> mean).clamp(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">6</span>))</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, ax <span class="kw">in</span> <span class="bu">enumerate</span>(axes.flat):</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    img <span class="op">=</span> denormalize(images[i]).cpu().permute(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>).numpy()</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>    ax.imshow(img)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>    ax.axis(<span class="st">'off'</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>    color <span class="op">=</span> <span class="st">'green'</span> <span class="cf">if</span> preds[i] <span class="op">==</span> labels[i] <span class="cf">else</span> <span class="st">'red'</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"true: </span><span class="sc">{</span>CLASSES[labels[i]]<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"pred: </span><span class="sc">{</span>CLASSES[preds[i]]<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>confidence[i]<span class="sc">.</span>item()<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)"</span>,</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>                 color<span class="op">=</span>color, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="cnn-architecture_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Green titles mark correct predictions, red titles mark mistakes. Common confusions you will likely see: cat vs dog, deer vs horse, automobile vs truck. These categories share visual features (four-legged mammals, wheeled vehicles) and are exactly where a small CNN without data augmentation struggles most.</p>
</section>
<section id="per-class-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="per-class-accuracy">5.3 Per-Class Accuracy</h3>
<p>A single overall accuracy hides which classes the model is actually good at. Computing accuracy per class reveals the imbalance:</p>
<div id="c08f992d" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>class_correct <span class="op">=</span> [<span class="dv">0</span>] <span class="op">*</span> <span class="dv">10</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>class_total   <span class="op">=</span> [<span class="dv">0</span>] <span class="op">*</span> <span class="dv">10</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>model.<span class="bu">eval</span>()</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x, y <span class="kw">in</span> test_loader:</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>        x, y <span class="op">=</span> x.to(device), y.to(device)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> model(x).argmax(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> c <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>            mask <span class="op">=</span> (y <span class="op">==</span> c)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>            class_correct[c] <span class="op">+=</span> (preds[mask] <span class="op">==</span> c).<span class="bu">sum</span>().item()</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>            class_total[c]   <span class="op">+=</span> mask.<span class="bu">sum</span>().item()</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Class'</span><span class="sc">:&lt;14}{</span><span class="st">'Accuracy'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>    acc <span class="op">=</span> class_correct[c] <span class="op">/</span> class_total[c]</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>CLASSES[c]<span class="sc">:&lt;14}{</span>acc<span class="op">*</span><span class="dv">100</span><span class="sc">:&gt;9.1f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class           Accuracy
airplane           78.3%
automobile         84.8%
bird               59.5%
cat                47.8%
deer               75.5%
dog                76.0%
frog               85.1%
horse              80.1%
ship               87.8%
truck              90.0%</code></pre>
</div>
</div>
<p>You will typically see the highest accuracy on visually distinctive classes (ship, truck, automobile) and the lowest on confusable ones (cat, bird, deer). This per-class view is what guides the next iteration of model design: which classes need more data, more capacity, or specialized augmentation.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>A <strong>VGG-style CNN</strong> stacks <code>[Conv -&gt; ReLU -&gt; Conv -&gt; ReLU -&gt; MaxPool]</code> blocks, doubling channels and halving spatial size at each block. The final feature map is flattened and passed through a small FC head to produce class logits.</li>
<li><strong><code>torchinfo.summary</code></strong> is the standard tool for inspecting a model before training: it shows layer-by-layer output shapes, parameter counts, and total memory. The first FC layer in a classical CNN almost always dominates the parameter count.</li>
<li>A typical <strong>training loop</strong> alternates a forward pass, loss computation, backward pass, and optimizer step, then evaluates on a held-out test set after each epoch. Plotting train and test curves together is the fastest way to detect overfitting.</li>
<li>After training, <strong>inference</strong> uses the same forward pass but inside a <code>torch.no_grad()</code> block (no gradient tracking, lower memory). Applying <code>softmax</code> to the logits gives class probabilities, and <code>argmax</code> gives the predicted class. Per-class accuracy reveals strengths and weaknesses that overall accuracy hides.</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Krizhevsky, A. (2009). <em>Learning Multiple Layers of Features from Tiny Images</em> (CIFAR-10 dataset).</li>
<li>Simonyan, K., and Zisserman, A. (2015). Very Deep Convolutional Networks for Large-Scale Image Recognition (VGG). <em>ICLR</em>.</li>
<li>Goodfellow, I., Bengio, Y., and Courville, A. (2016). <em>Deep Learning</em>. MIT Press.</li>
</ul>
</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further Reading</h2>
<ul>
<li><a href="https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html">PyTorch CIFAR-10 Tutorial</a></li>
<li><a href="https://github.com/TylerYep/torchinfo">torchinfo: Model summary in PyTorch</a></li>
<li><a href="https://cs231n.github.io/neural-networks-3/">CS231n: Training Neural Networks</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gli\.konkuk\.ac\.kr\/board\/lectures\/machine-learning");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>