{
  "hash": "41883ebe189f5beabc1f32363933e5db",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Lab3-1. Linear Regression from Scratch\"\njupyter: python3\n---\n\n\n\n\n[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/GLI-Lab/machine-learning-course/blob/students/exercises/lab03/linear-regression-scratch.ipynb)\n\n## Objectives\n\n- Understand how **modular layer classes** (Linear, Identity) serve as reusable building blocks for different model architectures.\n- Implement **Linear Regression** from scratch as a single-layer neural network using the same `Linear`, `Identity`, `MSELoss`, and `Optimizer` classes introduced in the lecture.\n- Build a clean `LinearRegression` class with `fit()` and `predict()` methods that directly orchestrates the forward pass, backward pass, and weight updates.\n- Visualize training dynamics (loss curves, MAE curves) and evaluate model performance on unseen test data.\n\n## 0. Setup\n\n::: {#ba1d8fe0 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nsns.set_theme(style='whitegrid', font_scale=1.2)\n```\n:::\n\n\n## 1. Preparing the Dataset\n\nWe load the London houses dataset, which contains 87 features (area, number of bedrooms, property type dummies, postcode dummies, etc.) and a target column `price`. The preparation follows the same four steps from the lecture: separate features from target, split into train/test, normalize, and confirm the shapes.\n\n::: {#d2a591c2 .cell execution_count=2}\n``` {.python .cell-code}\nfrom sklearn.model_selection import train_test_split\n\n# Load data\ndata = np.genfromtxt(\"../../data/london_houses_transformed.csv\", delimiter=\",\", skip_header=1)\nX = data[:, :-1]   # All columns except the last one (features)\nY = data[:, -1:]    # Last column only (target: price)\n\nprint(f\"Feature matrix X shape: {X.shape}\")\nprint(f\"Target vector  Y shape: {Y.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFeature matrix X shape: (3441, 87)\nTarget vector  Y shape: (3441, 1)\n```\n:::\n:::\n\n\nThe feature matrix has 3441 samples and 87 features. Each row represents one property listing, and the last column (`price`) is what we want to predict.\n\n::: {#9172b6f0 .cell execution_count=3}\n``` {.python .cell-code}\n# Train / Test split (80/20)\nX_train_raw, X_test_raw, Y_train_raw, Y_test_raw = train_test_split(\n    X, Y, test_size=0.2, random_state=15\n)\n\n# Normalize features (fit on training data only to avoid data leakage)\nX_mean, X_std = X_train_raw.mean(axis=0), X_train_raw.std(axis=0) + 1e-8\nX_train = (X_train_raw - X_mean) / X_std\nX_test  = (X_test_raw  - X_mean) / X_std\n\n# Normalize target\nY_mean, Y_std = Y_train_raw.mean(), Y_train_raw.std()\nY_train = (Y_train_raw - Y_mean) / Y_std\nY_test  = (Y_test_raw  - Y_mean) / Y_std\n\nN, D = X_train.shape\nprint(f\"Dataset: {X.shape[0]} total samples\")\nprint(f\"  Train: {N} | Test: {X_test.shape[0]}\")\nprint(f\"  Features (D): {D}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset: 3441 total samples\n  Train: 2752 | Test: 689\n  Features (D): 87\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## Why Normalize Using Only Training Statistics?\n\nWe compute the mean and standard deviation from the training set and apply them to both the training and test sets. If we computed statistics on the entire dataset (including the test set), the model would indirectly \"see\" information from the test set during training. This is called **data leakage** and leads to overly optimistic evaluation metrics that do not reflect real-world performance.\n:::\n\n## 2. Defining the Layer Building Blocks\n\nThese are the same modular layer classes from the lecture. Each class implements a `forward()` method that computes the output and caches values needed for backpropagation, and a `backward()` method that receives the upstream gradient and returns the downstream gradient.\n\n### 2.1 Linear Layer\n\n**Forward:**\n\n$$z = \\mathbf{x}\\mathbf{W}^\\top + b$$\n\n**Backward** (given upstream gradient $\\texttt{grad} = \\partial \\mathcal{L} / \\partial z$):\n\n$$\\frac{\\partial z}{\\partial \\mathbf{W}} = \\mathbf{x}, \\quad \\frac{\\partial z}{\\partial b} = 1, \\quad \\frac{\\partial z}{\\partial \\mathbf{x}} = \\mathbf{W}$$\n\n$$\\Longrightarrow \\qquad \\frac{\\partial \\mathcal{L}}{\\partial \\mathbf{W}} = (\\underbrace{\\frac{\\partial \\mathcal{L}}{\\partial z}}_{\\texttt{grad}})^{\\top} \\!\\cdot\\; \\underbrace{\\frac{\\partial z}{\\partial \\mathbf{W}}}_{\\mathbf{x}} = \\texttt{grad}^\\top \\mathbf{x}, \\qquad \\frac{\\partial \\mathcal{L}}{\\partial b} = \\sum_i \\texttt{grad}_i, \\qquad \\frac{\\partial \\mathcal{L}}{\\partial \\mathbf{x}} = \\underbrace{\\frac{\\partial \\mathcal{L}}{\\partial z}}_{\\texttt{grad}} \\!\\cdot\\; \\underbrace{\\frac{\\partial z}{\\partial \\mathbf{x}}}_{\\mathbf{W}} = \\texttt{grad}\\;\\mathbf{W}$$\n\n::: {#64f96003 .cell execution_count=4}\n``` {.python .cell-code}\nclass Linear:\n    def __init__(self, in_dims, out_dims):\n        # Xavier uniform initialization for stable gradients\n        bound = 1 / np.sqrt(in_dims)\n        self.W = np.random.uniform(-bound, bound, size=(out_dims, in_dims))\n        self.b = np.random.uniform(-bound, bound, size=(out_dims,))\n\n    def forward(self, x):\n        self.x = x                        # Cache input for backward pass\n        return x @ self.W.T + self.b      # z = X W^T + b\n\n    def backward(self, grad):\n        self.deltaW = grad.T @ self.x     # dL/dW = g^T @ x\n        self.deltab = grad.sum(axis=0)    # dL/db = sum of upstream gradients\n        return grad @ self.W              # dL/dX = g @ W (downstream gradient)\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Layer Verification\n\n::: {#a902506b .cell execution_count=5}\n``` {.python .cell-code}\n# Quick sanity check: create a Linear layer mapping 3 features to 1 output\nnp.random.seed(0)\ntest_layer = Linear(in_dims=3, out_dims=1)\ntest_input = np.array([[1.0, 2.0, 3.0],\n                        [4.0, 5.0, 6.0]])  # (2 samples, 3 features)\n\ntest_output = test_layer.forward(test_input)\nprint(f\"Input shape : {test_input.shape}\")\nprint(f\"Weight shape: {test_layer.W.shape}\")\nprint(f\"Bias shape  : {test_layer.b.shape}\")\nprint(f\"Output shape: {test_output.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput shape : (2, 3)\nWeight shape: (1, 3)\nBias shape  : (1,)\nOutput shape: (2, 1)\n```\n:::\n:::\n\n\nThe shapes confirm that our `Linear(3, 1)` layer correctly maps 2 samples of 3 features each to 2 samples of 1 output each.\n:::\n\n### 2.2 Identity Layer\n\n**Forward:**\n\n$$h(z) = z$$\n\n**Backward** (given upstream gradient $\\texttt{grad}$):\n\n$$\\frac{\\partial h}{\\partial z} = 1 \\qquad \\Longrightarrow \\qquad \\frac{\\partial \\mathcal{L}}{\\partial z} = \\underbrace{\\frac{\\partial \\mathcal{L}}{\\partial h}}_{\\texttt{grad}} \\cdot \\frac{\\partial h}{\\partial z} = \\texttt{grad} \\cdot 1 = \\texttt{grad}$$\n\n::: {#7d9251cc .cell execution_count=6}\n``` {.python .cell-code}\nclass Identity:\n    def forward(self, x):\n        return x\n\n    def backward(self, grad):\n        return grad\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Layer Verification\n\n::: {#8abc3904 .cell execution_count=7}\n``` {.python .cell-code}\n# Verify that Identity passes values through unchanged\ntest_identity = Identity()\ntest_z = np.array([[1.5, -2.0, 0.3]])\n\nout = test_identity.forward(test_z)\n\nprint(f\"Input : {test_z}\")\nprint(f\"Output: {out}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput : [[ 1.5 -2.   0.3]]\nOutput: [[ 1.5 -2.   0.3]]\n```\n:::\n:::\n\n\nBoth forward and backward pass the values through unchanged, confirming that `Identity` acts as a no-op activation.\n:::\n\n## 3. Defining the MSE Loss\n\n**Forward:**\n\n$$\\mathcal{L}_{\\text{MSE}} = \\frac{1}{N}\\sum_{i=1}^{N}(\\hat{y}_i - y_i)^2$$\n\n**Backward** (gradient with respect to predictions):\n\n$$\\frac{\\partial \\mathcal{L}}{\\partial \\hat{y}_i} = \\frac{2}{N}(\\hat{y}_i - y_i)$$\n\n::: {#ac4bd549 .cell execution_count=8}\n``` {.python .cell-code}\nclass MSELoss:\n    def forward(self, pred, true):\n        self.pred = pred\n        self.true = true\n        self.N = pred.shape[0]\n        return ((pred - true) ** 2).mean()\n\n    def backward(self):\n        return (2 / self.N) * (self.pred - self.true)\n\n    def __call__(self, pred, true):\n        return self.forward(pred, true)\n```\n:::\n\n\n## 4. Building the Linear Regression Model\n\nNow we assemble everything into a `LinearRegression` class with `fit()` and `predict()` methods. Unlike the MLP from the lecture, which used a generic container to chain an arbitrary list of blocks, linear regression needs only two layers: a single `Linear` layer and an `Identity` output activation. We manage these directly as instance attributes, which keeps the data flow explicit and easy to follow.\n\n::: {#e0952f30 .cell execution_count=9}\n``` {.python .cell-code}\nclass LinearRegression:\n    def __init__(self, input_dim, lr=0.01):\n        \"\"\"\n        Parameters\n        ----------\n        input_dim : int\n            Number of input features (D).\n        lr : float\n            Learning rate for gradient descent.\n        \"\"\"\n        self.linear   = Linear(input_dim, 1)\n        self.identity = Identity()\n        self.loss_func = MSELoss()\n        self.lr = lr\n\n    def predict(self, X):\n        \"\"\"Forward pass: Linear -> Identity.\"\"\"\n        z = self.linear.forward(X)\n        return self.identity.forward(z)\n\n    def _update(self):\n        \"\"\"Apply gradient descent to the Linear layer's parameters.\"\"\"\n        self.linear.W = self.linear.W - self.lr * self.linear.deltaW\n        self.linear.b = self.linear.b - self.lr * self.linear.deltab\n\n    def fit(self, X_train, Y_train, X_test, Y_test,\n            Y_mean, Y_std, epochs=5000, print_every=500):\n        \"\"\"\n        Train the model using full-batch gradient descent.\n\n        Parameters\n        ----------\n        X_train, Y_train : ndarray\n            Normalized training data.\n        X_test, Y_test : ndarray\n            Normalized test data (for monitoring only, not used for training).\n        Y_mean, Y_std : float\n            Statistics to convert MAE back to original price scale.\n        epochs : int\n            Number of training iterations.\n        print_every : int\n            Print progress every this many epochs.\n\n        Returns\n        -------\n        history : dict\n            Training and test loss/MAE recorded at every epoch.\n        \"\"\"\n        history = {\n            \"train_loss\": [], \"test_loss\": [],\n            \"train_mae\": [],  \"test_mae\": []\n        }\n\n        for epoch in range(epochs):\n            # --- Forward pass ---\n            prediction = self.predict(X_train)\n            loss = self.loss_func(prediction, Y_train)\n\n            # --- Backward pass (Identity then Linear) ---\n            grad = self.loss_func.backward()\n            grad = self.identity.backward(grad)\n            self.linear.backward(grad)\n\n            # --- Update weights ---\n            self._update()\n\n            # --- Record training metrics ---\n            history[\"train_loss\"].append(loss)\n            train_mae = np.abs(\n                prediction * Y_std + Y_mean - (Y_train * Y_std + Y_mean)\n            ).mean()\n            history[\"train_mae\"].append(train_mae)\n\n            # --- Evaluate on test set (no gradient computation) ---\n            test_pred = self.predict(X_test)\n            test_loss = ((test_pred - Y_test) ** 2).mean()\n            test_mae = np.abs(\n                test_pred * Y_std + Y_mean - (Y_test * Y_std + Y_mean)\n            ).mean()\n            history[\"test_loss\"].append(test_loss)\n            history[\"test_mae\"].append(test_mae)\n\n            # --- Print progress ---\n            if epoch % print_every == 0 or epoch == epochs - 1:\n                print(f\"  Epoch {epoch:4d} | \"\n                      f\"Train Loss: {loss:.6f} | Test Loss: {test_loss:.6f}\")\n\n        return history\n```\n:::\n\n\nThe `fit()` method follows the same three-step loop you saw in the lecture: forward, backward, update. The only addition is that we also evaluate on the test set at each epoch to monitor generalization. Note that the test set is **never** used to compute gradients or update weights.\n\n## 5. Training the Model\n\n### 5.1 Running the Training Loop\n\n::: {#b2e81815 .cell execution_count=10}\n``` {.python .cell-code}\nnp.random.seed(42)\n\nreg = LinearRegression(input_dim=D, lr=0.01)\nhistory = reg.fit(\n    X_train, Y_train,\n    X_test, Y_test,\n    Y_mean, Y_std,\n    epochs=5000,\n    print_every=500\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Epoch    0 | Train Loss: 1.223665 | Test Loss: 1.125681\n  Epoch  500 | Train Loss: 0.286441 | Test Loss: 0.303669\n  Epoch 1000 | Train Loss: 0.283401 | Test Loss: 0.297997\n  Epoch 1500 | Train Loss: 0.283299 | Test Loss: 0.297369\n  Epoch 2000 | Train Loss: 0.283295 | Test Loss: 0.297268\n  Epoch 2500 | Train Loss: 0.283295 | Test Loss: 0.297250\n  Epoch 3000 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 3500 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4000 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4500 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4999 | Train Loss: 0.283295 | Test Loss: 0.297246\n```\n:::\n:::\n\n\nYou should see both train and test loss decrease steadily. If the loss increases or produces `nan`, the learning rate is too large.\n\n### 5.2 Visualizing the Training Curves\n\n::: {#ae54ac18 .cell execution_count=11}\n``` {.python .cell-code}\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n\n# Left panel: MSE Loss\nax1.plot(history[\"train_loss\"], label=\"Train Loss\", color=\"#e74c3c\", linewidth=1.5)\nax1.plot(history[\"test_loss\"],  label=\"Test Loss\",  color=\"#3498db\", linewidth=1.5)\nax1.set_xlabel(\"Epoch\")\nax1.set_ylabel(\"MSE Loss (normalized)\")\nax1.set_title(\"Training vs Test Loss\")\nax1.legend()\nax1.grid(True, alpha=0.3)\n\n# Right panel: MAE in original price scale\nax2.plot(history[\"train_mae\"], label=\"Train MAE\", color=\"#e74c3c\", linewidth=1.5)\nax2.plot(history[\"test_mae\"],  label=\"Test MAE\",  color=\"#3498db\", linewidth=1.5)\nax2.set_xlabel(\"Epoch\")\nax2.set_ylabel(\"MAE (£)\")\nax2.set_title(\"Training vs Test MAE\")\nax2.legend()\nax2.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](linear-regression-scratch_files/figure-html/cell-12-output-1.png){}\n:::\n:::\n\n\nThe left plot shows the normalized MSE loss, which is useful for diagnosing training dynamics (is it converging? is it overfitting?). The right plot shows the Mean Absolute Error in pounds, which is more interpretable: it tells you, on average, how far off the model's price predictions are.\n\nFor linear regression, you should see the train and test curves staying very close together. If the test loss diverged upward while the train loss continued to drop, that would signal overfitting, but a linear model with 87 features and 2752 training samples has relatively little capacity to overfit.\n\n## 6. Evaluation on Unseen Test Data\n\n::: {#75e88c6d .cell execution_count=12}\n``` {.python .cell-code}\n# Generate predictions on the test set\nY_pred_norm = reg.predict(X_test)\n\n# Denormalize back to original price scale\nY_pred = Y_pred_norm * Y_std + Y_mean\nY_real = Y_test * Y_std + Y_mean\n\n# Compute final MAE\nmae = np.abs(Y_pred - Y_real).mean()\nprint(f\"TEST PREDICTIONS (UNSEEN DATA):\")\nprint(f\"  MAE: £{mae:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTEST PREDICTIONS (UNSEEN DATA):\n  MAE: £498,674\n```\n:::\n:::\n\n\nThis MAE tells you the average absolute prediction error in pounds. For London house prices ranging from under £1M to nearly £10M, an MAE around £500K-£600K is a reasonable starting point for a purely linear model with no feature engineering.\n\n### 6.1 Predicted vs Actual Scatter Plot\n\nA scatter plot of predicted versus actual prices is one of the most informative diagnostic visualizations for regression. Points on the diagonal line $\\hat{y} = y$ represent perfect predictions.\n\n::: {#b6ba2d9b .cell execution_count=13}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 7))\n\nax.scatter(Y_real / 1e6, Y_pred / 1e6, alpha=0.3, color='steelblue',\n           edgecolors='k', linewidths=0.3, s=20)\n\n# Plot the perfect prediction line\nlims = [0, Y_real.max() / 1e6 * 1.05]\nax.plot(lims, lims, 'r--', linewidth=1.5, label='Perfect prediction')\n\nax.set_xlabel(\"Actual Price (£M)\")\nax.set_ylabel(\"Predicted Price (£M)\")\nax.set_title(\"Predicted vs Actual House Prices\")\nax.legend()\nax.set_xlim(lims)\nax.set_ylim(lims)\nax.set_aspect('equal')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](linear-regression-scratch_files/figure-html/cell-14-output-1.png){}\n:::\n:::\n\n\nIf the model were perfect, all points would lie on the red dashed line. Systematic deviations (e.g., consistently under-predicting expensive houses) reveal limitations of the linear assumption and suggest where a more complex model like the MLP from the lecture might help.\n\n## 7. Comparing with the Closed-Form Solution\n\nLinear regression has an exact solution via the Normal Equation:\n\n$$\\hat{\\mathbf{w}} = (\\mathbf{X}^\\top \\mathbf{X})^{-1} \\mathbf{X}^\\top \\mathbf{Y}$$\n\nThis provides a useful reference point: if our gradient descent implementation is correct, the learned weights should be close to the closed-form solution.\n\n::: {#7ac7f9ad .cell execution_count=14}\n``` {.python .cell-code}\n# Prepend a column of ones for the bias term\nX_train_aug = np.hstack([np.ones((N, 1)), X_train])\nX_test_aug  = np.hstack([np.ones((X_test.shape[0], 1)), X_test])\n\n# Closed-form solution: w = (X^T X)^{-1} X^T Y\nw_closed = np.linalg.solve(X_train_aug.T @ X_train_aug,\n                           X_train_aug.T @ Y_train)\n\n# Evaluate the closed-form model on the test set\nY_pred_closed_norm = X_test_aug @ w_closed\nY_pred_closed = Y_pred_closed_norm * Y_std + Y_mean\n\nmae_closed = np.abs(Y_pred_closed - Y_real).mean()\nprint(f\"Gradient Descent MAE : £{mae:,.0f}\")\nprint(f\"Closed-Form MAE      : £{mae_closed:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGradient Descent MAE : £498,674\nClosed-Form MAE      : £498,674\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Why Use Gradient Descent If a Closed Form Exists?\n\nFor this dataset with 87 features, the Normal Equation is fast and exact. But the closed-form solution requires inverting a $D \\times D$ matrix, which costs $O(D^3)$. When $D$ reaches tens of thousands (e.g., NLP or image tasks), this inversion becomes infeasible. Gradient descent scales linearly with $D$ and generalizes naturally to nonlinear models (like the MLP from the lecture) where no closed-form solution exists. Practicing gradient descent on linear regression builds the foundation for everything that follows.\n:::\n\nIf the two MAE values are close, your gradient descent implementation is working correctly. A small gap can remain if gradient descent has not fully converged. You can try increasing `epochs` or tuning `lr` to close the gap further.\n\n## 8. Complete Code\n\n::: {#413bff52 .cell execution_count=15}\n``` {.python .cell-code}\nimport numpy as np\nfrom sklearn.model_selection import train_test_split\n\n# ============================================================\n# 1. Data Preparation\n# ============================================================\ndata = np.genfromtxt(\"../../data/london_houses_transformed.csv\", delimiter=\",\", skip_header=1)\nX = data[:, :-1]\nY = data[:, -1:]\n\nX_train_raw, X_test_raw, Y_train_raw, Y_test_raw = train_test_split(\n    X, Y, test_size=0.2, random_state=15\n)\n\nX_mean, X_std = X_train_raw.mean(axis=0), X_train_raw.std(axis=0) + 1e-8\nX_train = (X_train_raw - X_mean) / X_std\nX_test  = (X_test_raw  - X_mean) / X_std\n\nY_mean, Y_std = Y_train_raw.mean(), Y_train_raw.std()\nY_train = (Y_train_raw - Y_mean) / Y_std\nY_test  = (Y_test_raw  - Y_mean) / Y_std\n\nN, D = X_train.shape\n\n# ============================================================\n# 2. Building Blocks\n# ============================================================\nclass Linear:\n    def __init__(self, in_dims, out_dims):\n        bound = 1 / np.sqrt(in_dims)\n        self.W = np.random.uniform(-bound, bound, size=(out_dims, in_dims))\n        self.b = np.random.uniform(-bound, bound, size=(out_dims,))\n\n    def forward(self, x):\n        self.x = x\n        return x @ self.W.T + self.b\n\n    def backward(self, grad):\n        self.deltaW = grad.T @ self.x\n        self.deltab = grad.sum(axis=0)\n        return grad @ self.W\n\n\nclass Identity:\n    def forward(self, x):\n        return x\n\n    def backward(self, grad):\n        return grad\n\n\nclass MSELoss:\n    def forward(self, pred, true):\n        self.pred = pred\n        self.true = true\n        self.N = pred.shape[0]\n        return ((pred - true) ** 2).mean()\n\n    def backward(self):\n        return (2 / self.N) * (self.pred - self.true)\n\n    def __call__(self, pred, true):\n        return self.forward(pred, true)\n\n# ============================================================\n# 3. Linear Regression Model\n# ============================================================\nclass LinearRegression:\n    def __init__(self, input_dim, lr=0.01):\n        self.linear   = Linear(input_dim, 1)\n        self.identity = Identity()\n        self.loss_func = MSELoss()\n        self.lr = lr\n\n    def predict(self, X):\n        z = self.linear.forward(X)\n        return self.identity.forward(z)\n\n    def _update(self):\n        self.linear.W -= self.lr * self.linear.deltaW\n        self.linear.b -= self.lr * self.linear.deltab\n\n    def fit(self, X_train, Y_train, X_test, Y_test,\n            Y_mean, Y_std, epochs=5000, print_every=500):\n        history = {\n            \"train_loss\": [], \"test_loss\": [],\n            \"train_mae\": [],  \"test_mae\": []\n        }\n        for epoch in range(epochs):\n            prediction = self.predict(X_train)\n            loss = self.loss_func(prediction, Y_train)\n\n            grad = self.loss_func.backward()\n            grad = self.identity.backward(grad)\n            self.linear.backward(grad)\n            self._update()\n\n            history[\"train_loss\"].append(loss)\n            train_mae = np.abs(\n                prediction * Y_std + Y_mean - (Y_train * Y_std + Y_mean)\n            ).mean()\n            history[\"train_mae\"].append(train_mae)\n\n            test_pred = self.predict(X_test)\n            test_loss = ((test_pred - Y_test) ** 2).mean()\n            test_mae = np.abs(\n                test_pred * Y_std + Y_mean - (Y_test * Y_std + Y_mean)\n            ).mean()\n            history[\"test_loss\"].append(test_loss)\n            history[\"test_mae\"].append(test_mae)\n\n            if epoch % print_every == 0 or epoch == epochs - 1:\n                print(f\"  Epoch {epoch:4d} | \"\n                      f\"Train Loss: {loss:.6f} | Test Loss: {test_loss:.6f}\")\n        return history\n\n# ============================================================\n# 4. Train & Evaluate\n# ============================================================\nnp.random.seed(42)\nreg = LinearRegression(input_dim=D, lr=0.01)\nhistory = reg.fit(X_train, Y_train, X_test, Y_test, Y_mean, Y_std,\n                  epochs=5000, print_every=500)\n\nY_pred_norm = reg.predict(X_test)\nY_pred = Y_pred_norm * Y_std + Y_mean\nY_real = Y_test * Y_std + Y_mean\nmae = np.abs(Y_pred - Y_real).mean()\n\nprint(f\"\\nTEST RESULTS:\")\nprint(f\"  MAE: £{mae:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Epoch    0 | Train Loss: 1.223665 | Test Loss: 1.125681\n  Epoch  500 | Train Loss: 0.286441 | Test Loss: 0.303669\n  Epoch 1000 | Train Loss: 0.283401 | Test Loss: 0.297997\n  Epoch 1500 | Train Loss: 0.283299 | Test Loss: 0.297369\n  Epoch 2000 | Train Loss: 0.283295 | Test Loss: 0.297268\n  Epoch 2500 | Train Loss: 0.283295 | Test Loss: 0.297250\n  Epoch 3000 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 3500 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4000 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4500 | Train Loss: 0.283295 | Test Loss: 0.297246\n  Epoch 4999 | Train Loss: 0.283295 | Test Loss: 0.297246\n\nTEST RESULTS:\n  MAE: £498,674\n```\n:::\n:::\n\n\n## Summary\n\n- **Modular building blocks** (`Linear`, `Identity`, `MSELoss`) can be composed to build models of varying complexity. Linear Regression uses a single `Linear(D, 1)` followed by `Identity`, while the MLP from the lecture stacks multiple `Linear` and `Sigmoid` layers.\n- The **training loop** always follows the same three steps: forward pass (compute predictions), backward pass (propagate gradients), and parameter update (gradient descent). This pattern is identical whether the model is a simple linear regression or a deep neural network.\n- The `fit()` and `predict()` interface provides a clean separation between training and inference. During `fit()`, gradients are computed and weights are updated. During `predict()`, only the forward pass runs.\n- **Linear regression** serves as a useful baseline. Comparing its MAE (~£500K-£600K) with the MLP's MAE (~£480K) from the lecture shows how much improvement nonlinear hidden layers provide on this dataset.\n\n## References\n\n- Bishop, C. M. (2006). *Pattern Recognition and Machine Learning*. Springer.\n- Goodfellow, I., Bengio, Y., and Courville, A. (2016). *Deep Learning*. MIT Press.\n\n## Further Reading\n\n- [CS229 Lecture Notes on Linear Regression](https://cs229.stanford.edu/notes2022fall/main_notes.pdf)\n- [3Blue1Brown: But what is a neural network?](https://www.youtube.com/watch?v=aircAruvnKk)\n- [NumPy Documentation: Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)\n\n",
    "supporting": [
      "linear-regression-scratch_files"
    ],
    "filters": [],
    "includes": {}
  }
}